app:
  port: "8080"
  env: "development"

database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: ""
  database: "custos"
  charset: "utf8mb4"

jwt:
  secretKey: "dev-secret-change-me"
  accessTokenTTL: "15m"
  refreshTokenTTL: "168h"
