server:
  port: "8080"
  host: "0.0.0.0"
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

app:
  mode: "development"

jwt:
  secret: "your-jwt-secret-key-change-in-production"
  access_token_ttl: 15m
  refresh_token_ttl: 24h

logging:
  level: "info"
  format: "json"
  output: "stdout"

# OpenTelemetry observability configuration
observability:
  service_name: "clotho"
  exporter_url: "http://localhost:4317"
  sample_ratio: 1.0
  environment: "development"
  exporter_type: "stdout"

# gRPC client configurations
services:
  custos:
    address: "localhost:9001"
    timeout: 30s
    max_retries: 3

  orders:
    address: "localhost:9002"
    timeout: 30s
    max_retries: 3

  payments:
    address: "localhost:9003"
    timeout: 30s
    max_retries: 3

# Database (if needed for caching or session management)
database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "clotho"
  password: "password"
  database: "clotho_db"
  max_open_conns: 25
  max_idle_conns: 10
  conn_max_lifetime: 300s

# Redis cache
redis:
  address: "localhost:6379"
  password: ""
  db: 0
  pool_size: 10
  min_idle_conns: 5