server:
  port: "${SERVER_PORT:8080}"
  host: "${SERVER_HOST:0.0.0.0}"
  read_timeout: "${SERVER_READ_TIMEOUT:30s}"
  write_timeout: "${SERVER_WRITE_TIMEOUT:30s}"
  idle_timeout: "${SERVER_IDLE_TIMEOUT:60s}"

jwt:
  secret: "${JWT_SECRET:development-secret-key}"
  access_token_ttl: "${JWT_ACCESS_TOKEN_TTL:15m}"
  refresh_token_ttl: "${JWT_REFRESH_TOKEN_TTL:24h}"

logging:
  level: "${LOG_LEVEL:info}"
  format: "${LOG_FORMAT:json}"
  output: "${LOG_OUTPUT:stdout}"

# gRPC client configurations
services:
  custos:
    address: "${CUSTOS_GRPC_ADDRESS:localhost:9001}"
    timeout: "${CUSTOS_GRPC_TIMEOUT:30s}"
    max_retries: "${CUSTOS_GRPC_MAX_RETRIES:3}"

  orders:
    address: "${ORDERS_GRPC_ADDRESS:localhost:9002}"
    timeout: "${ORDERS_GRPC_TIMEOUT:30s}"
    max_retries: "${ORDERS_GRPC_MAX_RETRIES:3}"

  payments:
    address: "${PAYMENTS_GRPC_ADDRESS:localhost:9003}"
    timeout: "${PAYMENTS_GRPC_TIMEOUT:30s}"
    max_retries: "${PAYMENTS_GRPC_MAX_RETRIES:3}"

# Database (if needed for caching or session management)
database:
  driver: "${DB_DRIVER:mysql}"
  host: "${DB_HOST:localhost}"
  port: "${DB_PORT:3306}"
  username: "${DB_USERNAME:clotho}"
  password: "${DB_PASSWORD:password}"
  database: "${DB_NAME:clotho_db}"
  max_open_conns: "${DB_MAX_OPEN_CONNS:25}"
  max_idle_conns: "${DB_MAX_IDLE_CONNS:10}"
  conn_max_lifetime: "${DB_CONN_MAX_LIFETIME:300s}"

# Redis cache
redis:
  address: "${REDIS_ADDRESS:localhost:6379}"
  password: "${REDIS_PASSWORD:}"
  db: "${REDIS_DB:0}"
  pool_size: "${REDIS_POOL_SIZE:10}"
  min_idle_conns: "${REDIS_MIN_IDLE_CONNS:5}"