// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/proto/staff/v1/staff.proto

package staffv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Staff message represents a staff member
type Staff struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId           *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name             string                  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                  `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                  `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender           string                  `protobuf:"bytes,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday         *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Avatar           *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Department       string                  `protobuf:"bytes,9,opt,name=department,proto3" json:"department,omitempty"`
	Position         string                  `protobuf:"bytes,10,opt,name=position,proto3" json:"position,omitempty"`
	RoleId           string                  `protobuf:"bytes,11,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status           string                  `protobuf:"bytes,12,opt,name=status,proto3" json:"status,omitempty"`
	HireDate         *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=hire_date,json=hireDate,proto3" json:"hire_date,omitempty"`
	Salary           *wrapperspb.DoubleValue `protobuf:"bytes,14,opt,name=salary,proto3" json:"salary,omitempty"`
	Address          *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=address,proto3" json:"address,omitempty"`
	EmergencyContact *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
	Notes            *wrapperspb.StringValue `protobuf:"bytes,17,opt,name=notes,proto3" json:"notes,omitempty"`
	Skills           []string                `protobuf:"bytes,18,rep,name=skills,proto3" json:"skills,omitempty"`
	WorkingHours     *structpb.Value         `protobuf:"bytes,19,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"` // JSON object for flexible working hours
	IsAvailable      bool                    `protobuf:"varint,20,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,21,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp  `protobuf:"bytes,22,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{0}
}

func (x *Staff) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Staff) GetUserId() *wrapperspb.StringValue {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Staff) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Staff) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Staff) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Staff) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *Staff) GetBirthday() *wrapperspb.StringValue {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *Staff) GetAvatar() *wrapperspb.StringValue {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *Staff) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *Staff) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *Staff) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *Staff) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Staff) GetHireDate() *wrapperspb.StringValue {
	if x != nil {
		return x.HireDate
	}
	return nil
}

func (x *Staff) GetSalary() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *Staff) GetAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Staff) GetEmergencyContact() *wrapperspb.StringValue {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

func (x *Staff) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *Staff) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *Staff) GetWorkingHours() *structpb.Value {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *Staff) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *Staff) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Staff) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// StaffRole represents a staff role
type StaffRole struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                  `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []string                `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	IsDefault     bool                    `protobuf:"varint,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	SortOrder     int32                   `protobuf:"varint,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        string                  `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	StaffCount    int32                   `protobuf:"varint,9,opt,name=staff_count,json=staffCount,proto3" json:"staff_count,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffRole) Reset() {
	*x = StaffRole{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffRole) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffRole) ProtoMessage() {}

func (x *StaffRole) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffRole.ProtoReflect.Descriptor instead.
func (*StaffRole) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{1}
}

func (x *StaffRole) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StaffRole) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StaffRole) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *StaffRole) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *StaffRole) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *StaffRole) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *StaffRole) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *StaffRole) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StaffRole) GetStaffCount() int32 {
	if x != nil {
		return x.StaffCount
	}
	return 0
}

func (x *StaffRole) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StaffRole) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// StaffAvailability represents staff availability
type StaffAvailability struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StaffId       string                  `protobuf:"bytes,2,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	DayOfWeek     int32                   `protobuf:"varint,3,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"` // 0 = Sunday, 1 = Monday, ..., 6 = Saturday
	StartTime     string                  `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`    // HH:MM format
	EndTime       string                  `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`          // HH:MM format
	IsAvailable   bool                    `protobuf:"varint,6,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=notes,proto3" json:"notes,omitempty"`
	CreatedAt     *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffAvailability) Reset() {
	*x = StaffAvailability{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffAvailability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffAvailability) ProtoMessage() {}

func (x *StaffAvailability) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffAvailability.ProtoReflect.Descriptor instead.
func (*StaffAvailability) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{2}
}

func (x *StaffAvailability) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StaffAvailability) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *StaffAvailability) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *StaffAvailability) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *StaffAvailability) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *StaffAvailability) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *StaffAvailability) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *StaffAvailability) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StaffAvailability) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// AvailabilityItem represents an availability setting item
type AvailabilityItem struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	DayOfWeek     int32                   `protobuf:"varint,1,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"`
	StartTime     string                  `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime       string                  `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	IsAvailable   bool                    `protobuf:"varint,4,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	Notes         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=notes,proto3" json:"notes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvailabilityItem) Reset() {
	*x = AvailabilityItem{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvailabilityItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvailabilityItem) ProtoMessage() {}

func (x *AvailabilityItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvailabilityItem.ProtoReflect.Descriptor instead.
func (*AvailabilityItem) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{3}
}

func (x *AvailabilityItem) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

func (x *AvailabilityItem) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *AvailabilityItem) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *AvailabilityItem) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

func (x *AvailabilityItem) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

type CreateStaffRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Name             string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email            string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                  `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender           string                  `protobuf:"bytes,4,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday         *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Avatar           *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Department       string                  `protobuf:"bytes,7,opt,name=department,proto3" json:"department,omitempty"`
	Position         string                  `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`
	RoleId           string                  `protobuf:"bytes,9,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status           string                  `protobuf:"bytes,10,opt,name=status,proto3" json:"status,omitempty"`
	HireDate         *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=hire_date,json=hireDate,proto3" json:"hire_date,omitempty"`
	Salary           *wrapperspb.DoubleValue `protobuf:"bytes,12,opt,name=salary,proto3" json:"salary,omitempty"`
	Address          *wrapperspb.StringValue `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	EmergencyContact *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
	Notes            *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=notes,proto3" json:"notes,omitempty"`
	Skills           []string                `protobuf:"bytes,16,rep,name=skills,proto3" json:"skills,omitempty"`
	WorkingHours     *structpb.Value         `protobuf:"bytes,17,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	IsAvailable      bool                    `protobuf:"varint,18,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateStaffRequest) Reset() {
	*x = CreateStaffRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffRequest) ProtoMessage() {}

func (x *CreateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffRequest.ProtoReflect.Descriptor instead.
func (*CreateStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{4}
}

func (x *CreateStaffRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateStaffRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateStaffRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateStaffRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CreateStaffRequest) GetBirthday() *wrapperspb.StringValue {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *CreateStaffRequest) GetAvatar() *wrapperspb.StringValue {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *CreateStaffRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateStaffRequest) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *CreateStaffRequest) GetRoleId() string {
	if x != nil {
		return x.RoleId
	}
	return ""
}

func (x *CreateStaffRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CreateStaffRequest) GetHireDate() *wrapperspb.StringValue {
	if x != nil {
		return x.HireDate
	}
	return nil
}

func (x *CreateStaffRequest) GetSalary() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *CreateStaffRequest) GetAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *CreateStaffRequest) GetEmergencyContact() *wrapperspb.StringValue {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

func (x *CreateStaffRequest) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *CreateStaffRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *CreateStaffRequest) GetWorkingHours() *structpb.Value {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *CreateStaffRequest) GetIsAvailable() bool {
	if x != nil {
		return x.IsAvailable
	}
	return false
}

type CreateStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStaffResponse) Reset() {
	*x = CreateStaffResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStaffResponse) ProtoMessage() {}

func (x *CreateStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStaffResponse.ProtoReflect.Descriptor instead.
func (*CreateStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{5}
}

func (x *CreateStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type GetStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffRequest) Reset() {
	*x = GetStaffRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffRequest) ProtoMessage() {}

func (x *GetStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffRequest.ProtoReflect.Descriptor instead.
func (*GetStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{6}
}

func (x *GetStaffRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffResponse) Reset() {
	*x = GetStaffResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffResponse) ProtoMessage() {}

func (x *GetStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffResponse.ProtoReflect.Descriptor instead.
func (*GetStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{7}
}

func (x *GetStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type ListStaffRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Search        *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Department    *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=department,proto3" json:"department,omitempty"`
	RoleId        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status        *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	IsAvailable   *wrapperspb.BoolValue   `protobuf:"bytes,5,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	MinAge        *wrapperspb.Int32Value  `protobuf:"bytes,6,opt,name=min_age,json=minAge,proto3" json:"min_age,omitempty"`
	MaxAge        *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=max_age,json=maxAge,proto3" json:"max_age,omitempty"`
	Gender        *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Skills        []string                `protobuf:"bytes,9,rep,name=skills,proto3" json:"skills,omitempty"`
	Page          int32                   `protobuf:"varint,10,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                   `protobuf:"varint,11,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Sort          string                  `protobuf:"bytes,12,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                  `protobuf:"bytes,13,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffRequest) Reset() {
	*x = ListStaffRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffRequest) ProtoMessage() {}

func (x *ListStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffRequest.ProtoReflect.Descriptor instead.
func (*ListStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{8}
}

func (x *ListStaffRequest) GetSearch() *wrapperspb.StringValue {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *ListStaffRequest) GetDepartment() *wrapperspb.StringValue {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *ListStaffRequest) GetRoleId() *wrapperspb.StringValue {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *ListStaffRequest) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListStaffRequest) GetIsAvailable() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsAvailable
	}
	return nil
}

func (x *ListStaffRequest) GetMinAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.MinAge
	}
	return nil
}

func (x *ListStaffRequest) GetMaxAge() *wrapperspb.Int32Value {
	if x != nil {
		return x.MaxAge
	}
	return nil
}

func (x *ListStaffRequest) GetGender() *wrapperspb.StringValue {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *ListStaffRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *ListStaffRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStaffRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListStaffRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListStaffRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         []*Staff               `protobuf:"bytes,1,rep,name=staff,proto3" json:"staff,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStaffResponse) Reset() {
	*x = ListStaffResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStaffResponse) ProtoMessage() {}

func (x *ListStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStaffResponse.ProtoReflect.Descriptor instead.
func (*ListStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{9}
}

func (x *ListStaffResponse) GetStaff() []*Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *ListStaffResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListStaffResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListStaffResponse) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type UpdateStaffRequest struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email            *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Phone            *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender           *wrapperspb.StringValue `protobuf:"bytes,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday         *wrapperspb.StringValue `protobuf:"bytes,6,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Avatar           *wrapperspb.StringValue `protobuf:"bytes,7,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Department       *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=department,proto3" json:"department,omitempty"`
	Position         *wrapperspb.StringValue `protobuf:"bytes,9,opt,name=position,proto3" json:"position,omitempty"`
	RoleId           *wrapperspb.StringValue `protobuf:"bytes,10,opt,name=role_id,json=roleId,proto3" json:"role_id,omitempty"`
	Status           *wrapperspb.StringValue `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"`
	HireDate         *wrapperspb.StringValue `protobuf:"bytes,12,opt,name=hire_date,json=hireDate,proto3" json:"hire_date,omitempty"`
	Salary           *wrapperspb.DoubleValue `protobuf:"bytes,13,opt,name=salary,proto3" json:"salary,omitempty"`
	Address          *wrapperspb.StringValue `protobuf:"bytes,14,opt,name=address,proto3" json:"address,omitempty"`
	EmergencyContact *wrapperspb.StringValue `protobuf:"bytes,15,opt,name=emergency_contact,json=emergencyContact,proto3" json:"emergency_contact,omitempty"`
	Notes            *wrapperspb.StringValue `protobuf:"bytes,16,opt,name=notes,proto3" json:"notes,omitempty"`
	Skills           []string                `protobuf:"bytes,17,rep,name=skills,proto3" json:"skills,omitempty"`
	WorkingHours     *structpb.Value         `protobuf:"bytes,18,opt,name=working_hours,json=workingHours,proto3" json:"working_hours,omitempty"`
	IsAvailable      *wrapperspb.BoolValue   `protobuf:"bytes,19,opt,name=is_available,json=isAvailable,proto3" json:"is_available,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UpdateStaffRequest) Reset() {
	*x = UpdateStaffRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffRequest) ProtoMessage() {}

func (x *UpdateStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateStaffRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStaffRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateStaffRequest) GetEmail() *wrapperspb.StringValue {
	if x != nil {
		return x.Email
	}
	return nil
}

func (x *UpdateStaffRequest) GetPhone() *wrapperspb.StringValue {
	if x != nil {
		return x.Phone
	}
	return nil
}

func (x *UpdateStaffRequest) GetGender() *wrapperspb.StringValue {
	if x != nil {
		return x.Gender
	}
	return nil
}

func (x *UpdateStaffRequest) GetBirthday() *wrapperspb.StringValue {
	if x != nil {
		return x.Birthday
	}
	return nil
}

func (x *UpdateStaffRequest) GetAvatar() *wrapperspb.StringValue {
	if x != nil {
		return x.Avatar
	}
	return nil
}

func (x *UpdateStaffRequest) GetDepartment() *wrapperspb.StringValue {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *UpdateStaffRequest) GetPosition() *wrapperspb.StringValue {
	if x != nil {
		return x.Position
	}
	return nil
}

func (x *UpdateStaffRequest) GetRoleId() *wrapperspb.StringValue {
	if x != nil {
		return x.RoleId
	}
	return nil
}

func (x *UpdateStaffRequest) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UpdateStaffRequest) GetHireDate() *wrapperspb.StringValue {
	if x != nil {
		return x.HireDate
	}
	return nil
}

func (x *UpdateStaffRequest) GetSalary() *wrapperspb.DoubleValue {
	if x != nil {
		return x.Salary
	}
	return nil
}

func (x *UpdateStaffRequest) GetAddress() *wrapperspb.StringValue {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *UpdateStaffRequest) GetEmergencyContact() *wrapperspb.StringValue {
	if x != nil {
		return x.EmergencyContact
	}
	return nil
}

func (x *UpdateStaffRequest) GetNotes() *wrapperspb.StringValue {
	if x != nil {
		return x.Notes
	}
	return nil
}

func (x *UpdateStaffRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *UpdateStaffRequest) GetWorkingHours() *structpb.Value {
	if x != nil {
		return x.WorkingHours
	}
	return nil
}

func (x *UpdateStaffRequest) GetIsAvailable() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsAvailable
	}
	return nil
}

type UpdateStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffResponse) Reset() {
	*x = UpdateStaffResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffResponse) ProtoMessage() {}

func (x *UpdateStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffResponse.ProtoReflect.Descriptor instead.
func (*UpdateStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateStaffResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type DeleteStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStaffRequest) Reset() {
	*x = DeleteStaffRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffRequest) ProtoMessage() {}

func (x *DeleteStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffRequest.ProtoReflect.Descriptor instead.
func (*DeleteStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteStaffRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStaffResponse) Reset() {
	*x = DeleteStaffResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStaffResponse) ProtoMessage() {}

func (x *DeleteStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStaffResponse.ProtoReflect.Descriptor instead.
func (*DeleteStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{13}
}

type UpdateStaffStatusRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Reason        *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffStatusRequest) Reset() {
	*x = UpdateStaffStatusRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffStatusRequest) ProtoMessage() {}

func (x *UpdateStaffStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStaffStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateStaffStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateStaffStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateStaffStatusRequest) GetReason() *wrapperspb.StringValue {
	if x != nil {
		return x.Reason
	}
	return nil
}

type UpdateStaffStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         *Staff                 `protobuf:"bytes,1,opt,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStaffStatusResponse) Reset() {
	*x = UpdateStaffStatusResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStaffStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStaffStatusResponse) ProtoMessage() {}

func (x *UpdateStaffStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStaffStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateStaffStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateStaffStatusResponse) GetStaff() *Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type GetAvailableStaffRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Department    *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`
	Skills        []string                `protobuf:"bytes,2,rep,name=skills,proto3" json:"skills,omitempty"`
	TimeSlot      *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=time_slot,json=timeSlot,proto3" json:"time_slot,omitempty"` // Optional time slot filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableStaffRequest) Reset() {
	*x = GetAvailableStaffRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableStaffRequest) ProtoMessage() {}

func (x *GetAvailableStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableStaffRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{16}
}

func (x *GetAvailableStaffRequest) GetDepartment() *wrapperspb.StringValue {
	if x != nil {
		return x.Department
	}
	return nil
}

func (x *GetAvailableStaffRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *GetAvailableStaffRequest) GetTimeSlot() *wrapperspb.StringValue {
	if x != nil {
		return x.TimeSlot
	}
	return nil
}

type GetAvailableStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Staff         []*Staff               `protobuf:"bytes,1,rep,name=staff,proto3" json:"staff,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableStaffResponse) Reset() {
	*x = GetAvailableStaffResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableStaffResponse) ProtoMessage() {}

func (x *GetAvailableStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableStaffResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{17}
}

func (x *GetAvailableStaffResponse) GetStaff() []*Staff {
	if x != nil {
		return x.Staff
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Status        *wrapperspb.StringValue `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Sort          string                  `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	Order         string                  `protobuf:"bytes,3,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{18}
}

func (x *ListRolesRequest) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *ListRolesRequest) GetSort() string {
	if x != nil {
		return x.Sort
	}
	return ""
}

func (x *ListRolesRequest) GetOrder() string {
	if x != nil {
		return x.Order
	}
	return ""
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Roles         []*StaffRole           `protobuf:"bytes,1,rep,name=roles,proto3" json:"roles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{19}
}

func (x *ListRolesResponse) GetRoles() []*StaffRole {
	if x != nil {
		return x.Roles
	}
	return nil
}

type CreateRoleRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Code          string                  `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []string                `protobuf:"bytes,4,rep,name=permissions,proto3" json:"permissions,omitempty"`
	IsDefault     bool                    `protobuf:"varint,5,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	SortOrder     int32                   `protobuf:"varint,6,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        string                  `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleRequest) Reset() {
	*x = CreateRoleRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleRequest) ProtoMessage() {}

func (x *CreateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleRequest.ProtoReflect.Descriptor instead.
func (*CreateRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{20}
}

func (x *CreateRoleRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateRoleRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateRoleRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *CreateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *CreateRoleRequest) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

func (x *CreateRoleRequest) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *CreateRoleRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *StaffRole             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoleResponse) Reset() {
	*x = CreateRoleResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoleResponse) ProtoMessage() {}

func (x *CreateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoleResponse.ProtoReflect.Descriptor instead.
func (*CreateRoleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{21}
}

func (x *CreateRoleResponse) GetRole() *StaffRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type GetRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleRequest) Reset() {
	*x = GetRoleRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleRequest) ProtoMessage() {}

func (x *GetRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleRequest.ProtoReflect.Descriptor instead.
func (*GetRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{22}
}

func (x *GetRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *StaffRole             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRoleResponse) Reset() {
	*x = GetRoleResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRoleResponse) ProtoMessage() {}

func (x *GetRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRoleResponse.ProtoReflect.Descriptor instead.
func (*GetRoleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{23}
}

func (x *GetRoleResponse) GetRole() *StaffRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type UpdateRoleRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Id            string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *wrapperspb.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Code          *wrapperspb.StringValue `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Description   *wrapperspb.StringValue `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Permissions   []string                `protobuf:"bytes,5,rep,name=permissions,proto3" json:"permissions,omitempty"`
	IsDefault     *wrapperspb.BoolValue   `protobuf:"bytes,6,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	SortOrder     *wrapperspb.Int32Value  `protobuf:"bytes,7,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Status        *wrapperspb.StringValue `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleRequest) Reset() {
	*x = UpdateRoleRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleRequest) ProtoMessage() {}

func (x *UpdateRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{24}
}

func (x *UpdateRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateRoleRequest) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *UpdateRoleRequest) GetCode() *wrapperspb.StringValue {
	if x != nil {
		return x.Code
	}
	return nil
}

func (x *UpdateRoleRequest) GetDescription() *wrapperspb.StringValue {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *UpdateRoleRequest) GetPermissions() []string {
	if x != nil {
		return x.Permissions
	}
	return nil
}

func (x *UpdateRoleRequest) GetIsDefault() *wrapperspb.BoolValue {
	if x != nil {
		return x.IsDefault
	}
	return nil
}

func (x *UpdateRoleRequest) GetSortOrder() *wrapperspb.Int32Value {
	if x != nil {
		return x.SortOrder
	}
	return nil
}

func (x *UpdateRoleRequest) GetStatus() *wrapperspb.StringValue {
	if x != nil {
		return x.Status
	}
	return nil
}

type UpdateRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          *StaffRole             `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleResponse) Reset() {
	*x = UpdateRoleResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleResponse) ProtoMessage() {}

func (x *UpdateRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleResponse.ProtoReflect.Descriptor instead.
func (*UpdateRoleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{25}
}

func (x *UpdateRoleResponse) GetRole() *StaffRole {
	if x != nil {
		return x.Role
	}
	return nil
}

type DeleteRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleRequest) Reset() {
	*x = DeleteRoleRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleRequest) ProtoMessage() {}

func (x *DeleteRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleRequest.ProtoReflect.Descriptor instead.
func (*DeleteRoleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{26}
}

func (x *DeleteRoleRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteRoleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRoleResponse) Reset() {
	*x = DeleteRoleResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRoleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRoleResponse) ProtoMessage() {}

func (x *DeleteRoleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRoleResponse.ProtoReflect.Descriptor instead.
func (*DeleteRoleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{27}
}

type GetAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailabilityRequest) Reset() {
	*x = GetAvailabilityRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityRequest) ProtoMessage() {}

func (x *GetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{28}
}

func (x *GetAvailabilityRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

type GetAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Availabilities []*StaffAvailability   `protobuf:"bytes,1,rep,name=availabilities,proto3" json:"availabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetAvailabilityResponse) Reset() {
	*x = GetAvailabilityResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailabilityResponse) ProtoMessage() {}

func (x *GetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{29}
}

func (x *GetAvailabilityResponse) GetAvailabilities() []*StaffAvailability {
	if x != nil {
		return x.Availabilities
	}
	return nil
}

type SetAvailabilityRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StaffId        string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	Availabilities []*AvailabilityItem    `protobuf:"bytes,2,rep,name=availabilities,proto3" json:"availabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetAvailabilityRequest) Reset() {
	*x = SetAvailabilityRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvailabilityRequest) ProtoMessage() {}

func (x *SetAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*SetAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{30}
}

func (x *SetAvailabilityRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *SetAvailabilityRequest) GetAvailabilities() []*AvailabilityItem {
	if x != nil {
		return x.Availabilities
	}
	return nil
}

type SetAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Availabilities []*StaffAvailability   `protobuf:"bytes,1,rep,name=availabilities,proto3" json:"availabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SetAvailabilityResponse) Reset() {
	*x = SetAvailabilityResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAvailabilityResponse) ProtoMessage() {}

func (x *SetAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*SetAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{31}
}

func (x *SetAvailabilityResponse) GetAvailabilities() []*StaffAvailability {
	if x != nil {
		return x.Availabilities
	}
	return nil
}

type GetStaffAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StaffId       string                 `protobuf:"bytes,1,opt,name=staff_id,json=staffId,proto3" json:"staff_id,omitempty"`
	DayOfWeek     int32                  `protobuf:"varint,2,opt,name=day_of_week,json=dayOfWeek,proto3" json:"day_of_week,omitempty"` // Optional: get availability for specific day
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStaffAvailabilityRequest) Reset() {
	*x = GetStaffAvailabilityRequest{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffAvailabilityRequest) ProtoMessage() {}

func (x *GetStaffAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetStaffAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{32}
}

func (x *GetStaffAvailabilityRequest) GetStaffId() string {
	if x != nil {
		return x.StaffId
	}
	return ""
}

func (x *GetStaffAvailabilityRequest) GetDayOfWeek() int32 {
	if x != nil {
		return x.DayOfWeek
	}
	return 0
}

type GetStaffAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Availabilities []*StaffAvailability   `protobuf:"bytes,1,rep,name=availabilities,proto3" json:"availabilities,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetStaffAvailabilityResponse) Reset() {
	*x = GetStaffAvailabilityResponse{}
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStaffAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStaffAvailabilityResponse) ProtoMessage() {}

func (x *GetStaffAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_staff_v1_staff_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStaffAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetStaffAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_staff_v1_staff_proto_rawDescGZIP(), []int{33}
}

func (x *GetStaffAvailabilityResponse) GetAvailabilities() []*StaffAvailability {
	if x != nil {
		return x.Availabilities
	}
	return nil
}

var File_api_proto_staff_v1_staff_proto protoreflect.FileDescriptor

const file_api_proto_staff_v1_staff_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/staff/v1/staff.proto\x12\bstaff.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x99\a\n" +
	"\x05Staff\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x125\n" +
	"\auser_id\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\tR\x06gender\x128\n" +
	"\bbirthday\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\bbirthday\x124\n" +
	"\x06avatar\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x06avatar\x12\x1e\n" +
	"\n" +
	"department\x18\t \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\bposition\x18\n" +
	" \x01(\tR\bposition\x12\x17\n" +
	"\arole_id\x18\v \x01(\tR\x06roleId\x12\x16\n" +
	"\x06status\x18\f \x01(\tR\x06status\x129\n" +
	"\thire_date\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\bhireDate\x124\n" +
	"\x06salary\x18\x0e \x01(\v2\x1c.google.protobuf.DoubleValueR\x06salary\x126\n" +
	"\aaddress\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\aaddress\x12I\n" +
	"\x11emergency_contact\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\x10emergencyContact\x122\n" +
	"\x05notes\x18\x11 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12\x16\n" +
	"\x06skills\x18\x12 \x03(\tR\x06skills\x12;\n" +
	"\rworking_hours\x18\x13 \x01(\v2\x16.google.protobuf.ValueR\fworkingHours\x12!\n" +
	"\fis_available\x18\x14 \x01(\bR\visAvailable\x129\n" +
	"\n" +
	"created_at\x18\x15 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x92\x03\n" +
	"\tStaffRole\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"is_default\x18\x06 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"sort_order\x18\a \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\x12\x1f\n" +
	"\vstaff_count\x18\t \x01(\x05R\n" +
	"staffCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe5\x02\n" +
	"\x11StaffAvailability\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstaff_id\x18\x02 \x01(\tR\astaffId\x12\x1e\n" +
	"\vday_of_week\x18\x03 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x05 \x01(\tR\aendTime\x12!\n" +
	"\fis_available\x18\x06 \x01(\bR\visAvailable\x122\n" +
	"\x05notes\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc3\x01\n" +
	"\x10AvailabilityItem\x12\x1e\n" +
	"\vday_of_week\x18\x01 \x01(\x05R\tdayOfWeek\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12!\n" +
	"\fis_available\x18\x04 \x01(\bR\visAvailable\x122\n" +
	"\x05notes\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\"\xe9\x05\n" +
	"\x12CreateStaffRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\tR\x06gender\x128\n" +
	"\bbirthday\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\bbirthday\x124\n" +
	"\x06avatar\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\x06avatar\x12\x1e\n" +
	"\n" +
	"department\x18\a \x01(\tR\n" +
	"department\x12\x1a\n" +
	"\bposition\x18\b \x01(\tR\bposition\x12\x17\n" +
	"\arole_id\x18\t \x01(\tR\x06roleId\x12\x16\n" +
	"\x06status\x18\n" +
	" \x01(\tR\x06status\x129\n" +
	"\thire_date\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\bhireDate\x124\n" +
	"\x06salary\x18\f \x01(\v2\x1c.google.protobuf.DoubleValueR\x06salary\x126\n" +
	"\aaddress\x18\r \x01(\v2\x1c.google.protobuf.StringValueR\aaddress\x12I\n" +
	"\x11emergency_contact\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\x10emergencyContact\x122\n" +
	"\x05notes\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12\x16\n" +
	"\x06skills\x18\x10 \x03(\tR\x06skills\x12;\n" +
	"\rworking_hours\x18\x11 \x01(\v2\x16.google.protobuf.ValueR\fworkingHours\x12!\n" +
	"\fis_available\x18\x12 \x01(\bR\visAvailable\"<\n" +
	"\x13CreateStaffResponse\x12%\n" +
	"\x05staff\x18\x01 \x01(\v2\x0f.staff.v1.StaffR\x05staff\"!\n" +
	"\x0fGetStaffRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetStaffResponse\x12%\n" +
	"\x05staff\x18\x01 \x01(\v2\x0f.staff.v1.StaffR\x05staff\"\xc7\x04\n" +
	"\x10ListStaffRequest\x124\n" +
	"\x06search\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x06search\x12<\n" +
	"\n" +
	"department\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"department\x125\n" +
	"\arole_id\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06roleId\x124\n" +
	"\x06status\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x06status\x12=\n" +
	"\fis_available\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\visAvailable\x124\n" +
	"\amin_age\x18\x06 \x01(\v2\x1b.google.protobuf.Int32ValueR\x06minAge\x124\n" +
	"\amax_age\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\x06maxAge\x124\n" +
	"\x06gender\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x06gender\x12\x16\n" +
	"\x06skills\x18\t \x03(\tR\x06skills\x12\x12\n" +
	"\x04page\x18\n" +
	" \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\v \x01(\x05R\bpageSize\x12\x12\n" +
	"\x04sort\x18\f \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\r \x01(\tR\x05order\"\x81\x01\n" +
	"\x11ListStaffResponse\x12%\n" +
	"\x05staff\x18\x01 \x03(\v2\x0f.staff.v1.StaffR\x05staff\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"\x85\b\n" +
	"\x12UpdateStaffRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x122\n" +
	"\x05email\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x05email\x122\n" +
	"\x05phone\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\x05phone\x124\n" +
	"\x06gender\x18\x05 \x01(\v2\x1c.google.protobuf.StringValueR\x06gender\x128\n" +
	"\bbirthday\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\bbirthday\x124\n" +
	"\x06avatar\x18\a \x01(\v2\x1c.google.protobuf.StringValueR\x06avatar\x12<\n" +
	"\n" +
	"department\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"department\x128\n" +
	"\bposition\x18\t \x01(\v2\x1c.google.protobuf.StringValueR\bposition\x125\n" +
	"\arole_id\x18\n" +
	" \x01(\v2\x1c.google.protobuf.StringValueR\x06roleId\x124\n" +
	"\x06status\x18\v \x01(\v2\x1c.google.protobuf.StringValueR\x06status\x129\n" +
	"\thire_date\x18\f \x01(\v2\x1c.google.protobuf.StringValueR\bhireDate\x124\n" +
	"\x06salary\x18\r \x01(\v2\x1c.google.protobuf.DoubleValueR\x06salary\x126\n" +
	"\aaddress\x18\x0e \x01(\v2\x1c.google.protobuf.StringValueR\aaddress\x12I\n" +
	"\x11emergency_contact\x18\x0f \x01(\v2\x1c.google.protobuf.StringValueR\x10emergencyContact\x122\n" +
	"\x05notes\x18\x10 \x01(\v2\x1c.google.protobuf.StringValueR\x05notes\x12\x16\n" +
	"\x06skills\x18\x11 \x03(\tR\x06skills\x12;\n" +
	"\rworking_hours\x18\x12 \x01(\v2\x16.google.protobuf.ValueR\fworkingHours\x12=\n" +
	"\fis_available\x18\x13 \x01(\v2\x1a.google.protobuf.BoolValueR\visAvailable\"<\n" +
	"\x13UpdateStaffResponse\x12%\n" +
	"\x05staff\x18\x01 \x01(\v2\x0f.staff.v1.StaffR\x05staff\"$\n" +
	"\x12DeleteStaffRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x15\n" +
	"\x13DeleteStaffResponse\"x\n" +
	"\x18UpdateStaffStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x124\n" +
	"\x06reason\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x06reason\"B\n" +
	"\x19UpdateStaffStatusResponse\x12%\n" +
	"\x05staff\x18\x01 \x01(\v2\x0f.staff.v1.StaffR\x05staff\"\xab\x01\n" +
	"\x18GetAvailableStaffRequest\x12<\n" +
	"\n" +
	"department\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\n" +
	"department\x12\x16\n" +
	"\x06skills\x18\x02 \x03(\tR\x06skills\x129\n" +
	"\ttime_slot\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\btimeSlot\"B\n" +
	"\x19GetAvailableStaffResponse\x12%\n" +
	"\x05staff\x18\x01 \x03(\v2\x0f.staff.v1.StaffR\x05staff\"r\n" +
	"\x10ListRolesRequest\x124\n" +
	"\x06status\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x06status\x12\x12\n" +
	"\x04sort\x18\x02 \x01(\tR\x04sort\x12\x14\n" +
	"\x05order\x18\x03 \x01(\tR\x05order\">\n" +
	"\x11ListRolesResponse\x12)\n" +
	"\x05roles\x18\x01 \x03(\v2\x13.staff.v1.StaffRoleR\x05roles\"\xf3\x01\n" +
	"\x11CreateRoleRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12>\n" +
	"\vdescription\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12 \n" +
	"\vpermissions\x18\x04 \x03(\tR\vpermissions\x12\x1d\n" +
	"\n" +
	"is_default\x18\x05 \x01(\bR\tisDefault\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x06 \x01(\x05R\tsortOrder\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"=\n" +
	"\x12CreateRoleResponse\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x13.staff.v1.StaffRoleR\x04role\" \n" +
	"\x0eGetRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\":\n" +
	"\x0fGetRoleResponse\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x13.staff.v1.StaffRoleR\x04role\"\x96\x03\n" +
	"\x11UpdateRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04name\x18\x02 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x120\n" +
	"\x04code\x18\x03 \x01(\v2\x1c.google.protobuf.StringValueR\x04code\x12>\n" +
	"\vdescription\x18\x04 \x01(\v2\x1c.google.protobuf.StringValueR\vdescription\x12 \n" +
	"\vpermissions\x18\x05 \x03(\tR\vpermissions\x129\n" +
	"\n" +
	"is_default\x18\x06 \x01(\v2\x1a.google.protobuf.BoolValueR\tisDefault\x12:\n" +
	"\n" +
	"sort_order\x18\a \x01(\v2\x1b.google.protobuf.Int32ValueR\tsortOrder\x124\n" +
	"\x06status\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x06status\"=\n" +
	"\x12UpdateRoleResponse\x12'\n" +
	"\x04role\x18\x01 \x01(\v2\x13.staff.v1.StaffRoleR\x04role\"#\n" +
	"\x11DeleteRoleRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeleteRoleResponse\"3\n" +
	"\x16GetAvailabilityRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\"^\n" +
	"\x17GetAvailabilityResponse\x12C\n" +
	"\x0eavailabilities\x18\x01 \x03(\v2\x1b.staff.v1.StaffAvailabilityR\x0eavailabilities\"w\n" +
	"\x16SetAvailabilityRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12B\n" +
	"\x0eavailabilities\x18\x02 \x03(\v2\x1a.staff.v1.AvailabilityItemR\x0eavailabilities\"^\n" +
	"\x17SetAvailabilityResponse\x12C\n" +
	"\x0eavailabilities\x18\x01 \x03(\v2\x1b.staff.v1.StaffAvailabilityR\x0eavailabilities\"X\n" +
	"\x1bGetStaffAvailabilityRequest\x12\x19\n" +
	"\bstaff_id\x18\x01 \x01(\tR\astaffId\x12\x1e\n" +
	"\vday_of_week\x18\x02 \x01(\x05R\tdayOfWeek\"c\n" +
	"\x1cGetStaffAvailabilityResponse\x12C\n" +
	"\x0eavailabilities\x18\x01 \x03(\v2\x1b.staff.v1.StaffAvailabilityR\x0eavailabilities2\xaf\t\n" +
	"\fStaffService\x12J\n" +
	"\vCreateStaff\x12\x1c.staff.v1.CreateStaffRequest\x1a\x1d.staff.v1.CreateStaffResponse\x12A\n" +
	"\bGetStaff\x12\x19.staff.v1.GetStaffRequest\x1a\x1a.staff.v1.GetStaffResponse\x12D\n" +
	"\tListStaff\x12\x1a.staff.v1.ListStaffRequest\x1a\x1b.staff.v1.ListStaffResponse\x12J\n" +
	"\vUpdateStaff\x12\x1c.staff.v1.UpdateStaffRequest\x1a\x1d.staff.v1.UpdateStaffResponse\x12J\n" +
	"\vDeleteStaff\x12\x1c.staff.v1.DeleteStaffRequest\x1a\x1d.staff.v1.DeleteStaffResponse\x12\\\n" +
	"\x11UpdateStaffStatus\x12\".staff.v1.UpdateStaffStatusRequest\x1a#.staff.v1.UpdateStaffStatusResponse\x12\\\n" +
	"\x11GetAvailableStaff\x12\".staff.v1.GetAvailableStaffRequest\x1a#.staff.v1.GetAvailableStaffResponse\x12D\n" +
	"\tListRoles\x12\x1a.staff.v1.ListRolesRequest\x1a\x1b.staff.v1.ListRolesResponse\x12G\n" +
	"\n" +
	"CreateRole\x12\x1b.staff.v1.CreateRoleRequest\x1a\x1c.staff.v1.CreateRoleResponse\x12>\n" +
	"\aGetRole\x12\x18.staff.v1.GetRoleRequest\x1a\x19.staff.v1.GetRoleResponse\x12G\n" +
	"\n" +
	"UpdateRole\x12\x1b.staff.v1.UpdateRoleRequest\x1a\x1c.staff.v1.UpdateRoleResponse\x12G\n" +
	"\n" +
	"DeleteRole\x12\x1b.staff.v1.DeleteRoleRequest\x1a\x1c.staff.v1.DeleteRoleResponse\x12V\n" +
	"\x0fGetAvailability\x12 .staff.v1.GetAvailabilityRequest\x1a!.staff.v1.GetAvailabilityResponse\x12V\n" +
	"\x0fSetAvailability\x12 .staff.v1.SetAvailabilityRequest\x1a!.staff.v1.SetAvailabilityResponse\x12e\n" +
	"\x14GetStaffAvailability\x12%.staff.v1.GetStaffAvailabilityRequest\x1a&.staff.v1.GetStaffAvailabilityResponseB<Z:github.com/julesChu12/fly/staff/api/proto/staff/v1;staffv1b\x06proto3"

var (
	file_api_proto_staff_v1_staff_proto_rawDescOnce sync.Once
	file_api_proto_staff_v1_staff_proto_rawDescData []byte
)

func file_api_proto_staff_v1_staff_proto_rawDescGZIP() []byte {
	file_api_proto_staff_v1_staff_proto_rawDescOnce.Do(func() {
		file_api_proto_staff_v1_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_staff_v1_staff_proto_rawDesc), len(file_api_proto_staff_v1_staff_proto_rawDesc)))
	})
	return file_api_proto_staff_v1_staff_proto_rawDescData
}

var file_api_proto_staff_v1_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_api_proto_staff_v1_staff_proto_goTypes = []any{
	(*Staff)(nil),                        // 0: staff.v1.Staff
	(*StaffRole)(nil),                    // 1: staff.v1.StaffRole
	(*StaffAvailability)(nil),            // 2: staff.v1.StaffAvailability
	(*AvailabilityItem)(nil),             // 3: staff.v1.AvailabilityItem
	(*CreateStaffRequest)(nil),           // 4: staff.v1.CreateStaffRequest
	(*CreateStaffResponse)(nil),          // 5: staff.v1.CreateStaffResponse
	(*GetStaffRequest)(nil),              // 6: staff.v1.GetStaffRequest
	(*GetStaffResponse)(nil),             // 7: staff.v1.GetStaffResponse
	(*ListStaffRequest)(nil),             // 8: staff.v1.ListStaffRequest
	(*ListStaffResponse)(nil),            // 9: staff.v1.ListStaffResponse
	(*UpdateStaffRequest)(nil),           // 10: staff.v1.UpdateStaffRequest
	(*UpdateStaffResponse)(nil),          // 11: staff.v1.UpdateStaffResponse
	(*DeleteStaffRequest)(nil),           // 12: staff.v1.DeleteStaffRequest
	(*DeleteStaffResponse)(nil),          // 13: staff.v1.DeleteStaffResponse
	(*UpdateStaffStatusRequest)(nil),     // 14: staff.v1.UpdateStaffStatusRequest
	(*UpdateStaffStatusResponse)(nil),    // 15: staff.v1.UpdateStaffStatusResponse
	(*GetAvailableStaffRequest)(nil),     // 16: staff.v1.GetAvailableStaffRequest
	(*GetAvailableStaffResponse)(nil),    // 17: staff.v1.GetAvailableStaffResponse
	(*ListRolesRequest)(nil),             // 18: staff.v1.ListRolesRequest
	(*ListRolesResponse)(nil),            // 19: staff.v1.ListRolesResponse
	(*CreateRoleRequest)(nil),            // 20: staff.v1.CreateRoleRequest
	(*CreateRoleResponse)(nil),           // 21: staff.v1.CreateRoleResponse
	(*GetRoleRequest)(nil),               // 22: staff.v1.GetRoleRequest
	(*GetRoleResponse)(nil),              // 23: staff.v1.GetRoleResponse
	(*UpdateRoleRequest)(nil),            // 24: staff.v1.UpdateRoleRequest
	(*UpdateRoleResponse)(nil),           // 25: staff.v1.UpdateRoleResponse
	(*DeleteRoleRequest)(nil),            // 26: staff.v1.DeleteRoleRequest
	(*DeleteRoleResponse)(nil),           // 27: staff.v1.DeleteRoleResponse
	(*GetAvailabilityRequest)(nil),       // 28: staff.v1.GetAvailabilityRequest
	(*GetAvailabilityResponse)(nil),      // 29: staff.v1.GetAvailabilityResponse
	(*SetAvailabilityRequest)(nil),       // 30: staff.v1.SetAvailabilityRequest
	(*SetAvailabilityResponse)(nil),      // 31: staff.v1.SetAvailabilityResponse
	(*GetStaffAvailabilityRequest)(nil),  // 32: staff.v1.GetStaffAvailabilityRequest
	(*GetStaffAvailabilityResponse)(nil), // 33: staff.v1.GetStaffAvailabilityResponse
	(*wrapperspb.StringValue)(nil),       // 34: google.protobuf.StringValue
	(*wrapperspb.DoubleValue)(nil),       // 35: google.protobuf.DoubleValue
	(*structpb.Value)(nil),               // 36: google.protobuf.Value
	(*timestamppb.Timestamp)(nil),        // 37: google.protobuf.Timestamp
	(*wrapperspb.BoolValue)(nil),         // 38: google.protobuf.BoolValue
	(*wrapperspb.Int32Value)(nil),        // 39: google.protobuf.Int32Value
}
var file_api_proto_staff_v1_staff_proto_depIdxs = []int32{
	34, // 0: staff.v1.Staff.user_id:type_name -> google.protobuf.StringValue
	34, // 1: staff.v1.Staff.birthday:type_name -> google.protobuf.StringValue
	34, // 2: staff.v1.Staff.avatar:type_name -> google.protobuf.StringValue
	34, // 3: staff.v1.Staff.hire_date:type_name -> google.protobuf.StringValue
	35, // 4: staff.v1.Staff.salary:type_name -> google.protobuf.DoubleValue
	34, // 5: staff.v1.Staff.address:type_name -> google.protobuf.StringValue
	34, // 6: staff.v1.Staff.emergency_contact:type_name -> google.protobuf.StringValue
	34, // 7: staff.v1.Staff.notes:type_name -> google.protobuf.StringValue
	36, // 8: staff.v1.Staff.working_hours:type_name -> google.protobuf.Value
	37, // 9: staff.v1.Staff.created_at:type_name -> google.protobuf.Timestamp
	37, // 10: staff.v1.Staff.updated_at:type_name -> google.protobuf.Timestamp
	34, // 11: staff.v1.StaffRole.description:type_name -> google.protobuf.StringValue
	37, // 12: staff.v1.StaffRole.created_at:type_name -> google.protobuf.Timestamp
	37, // 13: staff.v1.StaffRole.updated_at:type_name -> google.protobuf.Timestamp
	34, // 14: staff.v1.StaffAvailability.notes:type_name -> google.protobuf.StringValue
	37, // 15: staff.v1.StaffAvailability.created_at:type_name -> google.protobuf.Timestamp
	37, // 16: staff.v1.StaffAvailability.updated_at:type_name -> google.protobuf.Timestamp
	34, // 17: staff.v1.AvailabilityItem.notes:type_name -> google.protobuf.StringValue
	34, // 18: staff.v1.CreateStaffRequest.birthday:type_name -> google.protobuf.StringValue
	34, // 19: staff.v1.CreateStaffRequest.avatar:type_name -> google.protobuf.StringValue
	34, // 20: staff.v1.CreateStaffRequest.hire_date:type_name -> google.protobuf.StringValue
	35, // 21: staff.v1.CreateStaffRequest.salary:type_name -> google.protobuf.DoubleValue
	34, // 22: staff.v1.CreateStaffRequest.address:type_name -> google.protobuf.StringValue
	34, // 23: staff.v1.CreateStaffRequest.emergency_contact:type_name -> google.protobuf.StringValue
	34, // 24: staff.v1.CreateStaffRequest.notes:type_name -> google.protobuf.StringValue
	36, // 25: staff.v1.CreateStaffRequest.working_hours:type_name -> google.protobuf.Value
	0,  // 26: staff.v1.CreateStaffResponse.staff:type_name -> staff.v1.Staff
	0,  // 27: staff.v1.GetStaffResponse.staff:type_name -> staff.v1.Staff
	34, // 28: staff.v1.ListStaffRequest.search:type_name -> google.protobuf.StringValue
	34, // 29: staff.v1.ListStaffRequest.department:type_name -> google.protobuf.StringValue
	34, // 30: staff.v1.ListStaffRequest.role_id:type_name -> google.protobuf.StringValue
	34, // 31: staff.v1.ListStaffRequest.status:type_name -> google.protobuf.StringValue
	38, // 32: staff.v1.ListStaffRequest.is_available:type_name -> google.protobuf.BoolValue
	39, // 33: staff.v1.ListStaffRequest.min_age:type_name -> google.protobuf.Int32Value
	39, // 34: staff.v1.ListStaffRequest.max_age:type_name -> google.protobuf.Int32Value
	34, // 35: staff.v1.ListStaffRequest.gender:type_name -> google.protobuf.StringValue
	0,  // 36: staff.v1.ListStaffResponse.staff:type_name -> staff.v1.Staff
	34, // 37: staff.v1.UpdateStaffRequest.name:type_name -> google.protobuf.StringValue
	34, // 38: staff.v1.UpdateStaffRequest.email:type_name -> google.protobuf.StringValue
	34, // 39: staff.v1.UpdateStaffRequest.phone:type_name -> google.protobuf.StringValue
	34, // 40: staff.v1.UpdateStaffRequest.gender:type_name -> google.protobuf.StringValue
	34, // 41: staff.v1.UpdateStaffRequest.birthday:type_name -> google.protobuf.StringValue
	34, // 42: staff.v1.UpdateStaffRequest.avatar:type_name -> google.protobuf.StringValue
	34, // 43: staff.v1.UpdateStaffRequest.department:type_name -> google.protobuf.StringValue
	34, // 44: staff.v1.UpdateStaffRequest.position:type_name -> google.protobuf.StringValue
	34, // 45: staff.v1.UpdateStaffRequest.role_id:type_name -> google.protobuf.StringValue
	34, // 46: staff.v1.UpdateStaffRequest.status:type_name -> google.protobuf.StringValue
	34, // 47: staff.v1.UpdateStaffRequest.hire_date:type_name -> google.protobuf.StringValue
	35, // 48: staff.v1.UpdateStaffRequest.salary:type_name -> google.protobuf.DoubleValue
	34, // 49: staff.v1.UpdateStaffRequest.address:type_name -> google.protobuf.StringValue
	34, // 50: staff.v1.UpdateStaffRequest.emergency_contact:type_name -> google.protobuf.StringValue
	34, // 51: staff.v1.UpdateStaffRequest.notes:type_name -> google.protobuf.StringValue
	36, // 52: staff.v1.UpdateStaffRequest.working_hours:type_name -> google.protobuf.Value
	38, // 53: staff.v1.UpdateStaffRequest.is_available:type_name -> google.protobuf.BoolValue
	0,  // 54: staff.v1.UpdateStaffResponse.staff:type_name -> staff.v1.Staff
	34, // 55: staff.v1.UpdateStaffStatusRequest.reason:type_name -> google.protobuf.StringValue
	0,  // 56: staff.v1.UpdateStaffStatusResponse.staff:type_name -> staff.v1.Staff
	34, // 57: staff.v1.GetAvailableStaffRequest.department:type_name -> google.protobuf.StringValue
	34, // 58: staff.v1.GetAvailableStaffRequest.time_slot:type_name -> google.protobuf.StringValue
	0,  // 59: staff.v1.GetAvailableStaffResponse.staff:type_name -> staff.v1.Staff
	34, // 60: staff.v1.ListRolesRequest.status:type_name -> google.protobuf.StringValue
	1,  // 61: staff.v1.ListRolesResponse.roles:type_name -> staff.v1.StaffRole
	34, // 62: staff.v1.CreateRoleRequest.description:type_name -> google.protobuf.StringValue
	1,  // 63: staff.v1.CreateRoleResponse.role:type_name -> staff.v1.StaffRole
	1,  // 64: staff.v1.GetRoleResponse.role:type_name -> staff.v1.StaffRole
	34, // 65: staff.v1.UpdateRoleRequest.name:type_name -> google.protobuf.StringValue
	34, // 66: staff.v1.UpdateRoleRequest.code:type_name -> google.protobuf.StringValue
	34, // 67: staff.v1.UpdateRoleRequest.description:type_name -> google.protobuf.StringValue
	38, // 68: staff.v1.UpdateRoleRequest.is_default:type_name -> google.protobuf.BoolValue
	39, // 69: staff.v1.UpdateRoleRequest.sort_order:type_name -> google.protobuf.Int32Value
	34, // 70: staff.v1.UpdateRoleRequest.status:type_name -> google.protobuf.StringValue
	1,  // 71: staff.v1.UpdateRoleResponse.role:type_name -> staff.v1.StaffRole
	2,  // 72: staff.v1.GetAvailabilityResponse.availabilities:type_name -> staff.v1.StaffAvailability
	3,  // 73: staff.v1.SetAvailabilityRequest.availabilities:type_name -> staff.v1.AvailabilityItem
	2,  // 74: staff.v1.SetAvailabilityResponse.availabilities:type_name -> staff.v1.StaffAvailability
	2,  // 75: staff.v1.GetStaffAvailabilityResponse.availabilities:type_name -> staff.v1.StaffAvailability
	4,  // 76: staff.v1.StaffService.CreateStaff:input_type -> staff.v1.CreateStaffRequest
	6,  // 77: staff.v1.StaffService.GetStaff:input_type -> staff.v1.GetStaffRequest
	8,  // 78: staff.v1.StaffService.ListStaff:input_type -> staff.v1.ListStaffRequest
	10, // 79: staff.v1.StaffService.UpdateStaff:input_type -> staff.v1.UpdateStaffRequest
	12, // 80: staff.v1.StaffService.DeleteStaff:input_type -> staff.v1.DeleteStaffRequest
	14, // 81: staff.v1.StaffService.UpdateStaffStatus:input_type -> staff.v1.UpdateStaffStatusRequest
	16, // 82: staff.v1.StaffService.GetAvailableStaff:input_type -> staff.v1.GetAvailableStaffRequest
	18, // 83: staff.v1.StaffService.ListRoles:input_type -> staff.v1.ListRolesRequest
	20, // 84: staff.v1.StaffService.CreateRole:input_type -> staff.v1.CreateRoleRequest
	22, // 85: staff.v1.StaffService.GetRole:input_type -> staff.v1.GetRoleRequest
	24, // 86: staff.v1.StaffService.UpdateRole:input_type -> staff.v1.UpdateRoleRequest
	26, // 87: staff.v1.StaffService.DeleteRole:input_type -> staff.v1.DeleteRoleRequest
	28, // 88: staff.v1.StaffService.GetAvailability:input_type -> staff.v1.GetAvailabilityRequest
	30, // 89: staff.v1.StaffService.SetAvailability:input_type -> staff.v1.SetAvailabilityRequest
	32, // 90: staff.v1.StaffService.GetStaffAvailability:input_type -> staff.v1.GetStaffAvailabilityRequest
	5,  // 91: staff.v1.StaffService.CreateStaff:output_type -> staff.v1.CreateStaffResponse
	7,  // 92: staff.v1.StaffService.GetStaff:output_type -> staff.v1.GetStaffResponse
	9,  // 93: staff.v1.StaffService.ListStaff:output_type -> staff.v1.ListStaffResponse
	11, // 94: staff.v1.StaffService.UpdateStaff:output_type -> staff.v1.UpdateStaffResponse
	13, // 95: staff.v1.StaffService.DeleteStaff:output_type -> staff.v1.DeleteStaffResponse
	15, // 96: staff.v1.StaffService.UpdateStaffStatus:output_type -> staff.v1.UpdateStaffStatusResponse
	17, // 97: staff.v1.StaffService.GetAvailableStaff:output_type -> staff.v1.GetAvailableStaffResponse
	19, // 98: staff.v1.StaffService.ListRoles:output_type -> staff.v1.ListRolesResponse
	21, // 99: staff.v1.StaffService.CreateRole:output_type -> staff.v1.CreateRoleResponse
	23, // 100: staff.v1.StaffService.GetRole:output_type -> staff.v1.GetRoleResponse
	25, // 101: staff.v1.StaffService.UpdateRole:output_type -> staff.v1.UpdateRoleResponse
	27, // 102: staff.v1.StaffService.DeleteRole:output_type -> staff.v1.DeleteRoleResponse
	29, // 103: staff.v1.StaffService.GetAvailability:output_type -> staff.v1.GetAvailabilityResponse
	31, // 104: staff.v1.StaffService.SetAvailability:output_type -> staff.v1.SetAvailabilityResponse
	33, // 105: staff.v1.StaffService.GetStaffAvailability:output_type -> staff.v1.GetStaffAvailabilityResponse
	91, // [91:106] is the sub-list for method output_type
	76, // [76:91] is the sub-list for method input_type
	76, // [76:76] is the sub-list for extension type_name
	76, // [76:76] is the sub-list for extension extendee
	0,  // [0:76] is the sub-list for field type_name
}

func init() { file_api_proto_staff_v1_staff_proto_init() }
func file_api_proto_staff_v1_staff_proto_init() {
	if File_api_proto_staff_v1_staff_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_staff_v1_staff_proto_rawDesc), len(file_api_proto_staff_v1_staff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_staff_v1_staff_proto_goTypes,
		DependencyIndexes: file_api_proto_staff_v1_staff_proto_depIdxs,
		MessageInfos:      file_api_proto_staff_v1_staff_proto_msgTypes,
	}.Build()
	File_api_proto_staff_v1_staff_proto = out.File
	file_api_proto_staff_v1_staff_proto_goTypes = nil
	file_api_proto_staff_v1_staff_proto_depIdxs = nil
}
