// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/plutus.proto

package plutusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wallet messages
type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	CustomerId    uint32                 `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Balance       float64                `protobuf:"fixed64,4,opt,name=balance,proto3" json:"balance,omitempty"`
	Currency      string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_api_proto_plutus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wallet) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Wallet) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Wallet) GetBalance() float64 {
	if x != nil {
		return x.Balance
	}
	return 0
}

func (x *Wallet) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Wallet) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Wallet) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Wallet) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Transaction messages
type Transaction struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       uint32                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WalletId       uint32                 `protobuf:"varint,3,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	OrderId        uint32                 `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Amount         float64                `protobuf:"fixed64,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Channel        string                 `protobuf:"bytes,8,opt,name=channel,proto3" json:"channel,omitempty"`
	Status         string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ReferenceNo    string                 `protobuf:"bytes,11,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
	Meta           string                 `protobuf:"bytes,12,opt,name=meta,proto3" json:"meta,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt      *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_api_proto_plutus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetTenantId() uint32 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Transaction) GetWalletId() uint32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *Transaction) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *Transaction) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Transaction) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Transaction) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Transaction) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *Transaction) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Transaction) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *Transaction) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

func (x *Transaction) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

func (x *Transaction) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Transaction) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request/Response messages for Wallet
type CreateWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletRequest) Reset() {
	*x = CreateWalletRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletRequest) ProtoMessage() {}

func (x *CreateWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletRequest.ProtoReflect.Descriptor instead.
func (*CreateWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{2}
}

func (x *CreateWalletRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateWalletRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreateWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWalletResponse) Reset() {
	*x = CreateWalletResponse{}
	mi := &file_api_proto_plutus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWalletResponse) ProtoMessage() {}

func (x *CreateWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWalletResponse.ProtoReflect.Descriptor instead.
func (*CreateWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{3}
}

func (x *CreateWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type GetWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletRequest) Reset() {
	*x = GetWalletRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletRequest) ProtoMessage() {}

func (x *GetWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletRequest.ProtoReflect.Descriptor instead.
func (*GetWalletRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{4}
}

func (x *GetWalletRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetWalletByCustomerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletByCustomerIDRequest) Reset() {
	*x = GetWalletByCustomerIDRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletByCustomerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletByCustomerIDRequest) ProtoMessage() {}

func (x *GetWalletByCustomerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletByCustomerIDRequest.ProtoReflect.Descriptor instead.
func (*GetWalletByCustomerIDRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{5}
}

func (x *GetWalletByCustomerIDRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type GetWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallet        *Wallet                `protobuf:"bytes,1,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWalletResponse) Reset() {
	*x = GetWalletResponse{}
	mi := &file_api_proto_plutus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWalletResponse) ProtoMessage() {}

func (x *GetWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWalletResponse.ProtoReflect.Descriptor instead.
func (*GetWalletResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{6}
}

func (x *GetWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

type ListWalletsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsRequest) Reset() {
	*x = ListWalletsRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsRequest) ProtoMessage() {}

func (x *ListWalletsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsRequest.ProtoReflect.Descriptor instead.
func (*ListWalletsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{7}
}

func (x *ListWalletsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWalletsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListWalletsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wallets       []*Wallet              `protobuf:"bytes,1,rep,name=wallets,proto3" json:"wallets,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListWalletsResponse) Reset() {
	*x = ListWalletsResponse{}
	mi := &file_api_proto_plutus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListWalletsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListWalletsResponse) ProtoMessage() {}

func (x *ListWalletsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListWalletsResponse.ProtoReflect.Descriptor instead.
func (*ListWalletsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{8}
}

func (x *ListWalletsResponse) GetWallets() []*Wallet {
	if x != nil {
		return x.Wallets
	}
	return nil
}

func (x *ListWalletsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListWalletsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListWalletsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Request/Response messages for Transaction
type RechargeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Channel        string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ReferenceNo    string                 `protobuf:"bytes,6,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
	Meta           string                 `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RechargeRequest) Reset() {
	*x = RechargeRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RechargeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RechargeRequest) ProtoMessage() {}

func (x *RechargeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RechargeRequest.ProtoReflect.Descriptor instead.
func (*RechargeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{9}
}

func (x *RechargeRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *RechargeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RechargeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RechargeRequest) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *RechargeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RechargeRequest) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

func (x *RechargeRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type ConsumeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	OrderId        uint32                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Meta           string                 `protobuf:"bytes,6,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ConsumeRequest) Reset() {
	*x = ConsumeRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsumeRequest) ProtoMessage() {}

func (x *ConsumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsumeRequest.ProtoReflect.Descriptor instead.
func (*ConsumeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{10}
}

func (x *ConsumeRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *ConsumeRequest) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *ConsumeRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ConsumeRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ConsumeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ConsumeRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type RefundRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerId     uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	OrderId        uint32                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount         float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ReferenceNo    string                 `protobuf:"bytes,6,opt,name=reference_no,json=referenceNo,proto3" json:"reference_no,omitempty"`
	Meta           string                 `protobuf:"bytes,7,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RefundRequest) Reset() {
	*x = RefundRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefundRequest) ProtoMessage() {}

func (x *RefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefundRequest.ProtoReflect.Descriptor instead.
func (*RefundRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{11}
}

func (x *RefundRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *RefundRequest) GetOrderId() uint32 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *RefundRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *RefundRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RefundRequest) GetReferenceNo() string {
	if x != nil {
		return x.ReferenceNo
	}
	return ""
}

func (x *RefundRequest) GetMeta() string {
	if x != nil {
		return x.Meta
	}
	return ""
}

type TransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transaction   *Transaction           `protobuf:"bytes,1,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionResponse) Reset() {
	*x = TransactionResponse{}
	mi := &file_api_proto_plutus_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionResponse) ProtoMessage() {}

func (x *TransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionResponse.ProtoReflect.Descriptor instead.
func (*TransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{12}
}

func (x *TransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{13}
}

func (x *GetTransactionRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      uint32                 `protobuf:"varint,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsRequest) Reset() {
	*x = ListTransactionsRequest{}
	mi := &file_api_proto_plutus_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsRequest) ProtoMessage() {}

func (x *ListTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsRequest.ProtoReflect.Descriptor instead.
func (*ListTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{14}
}

func (x *ListTransactionsRequest) GetWalletId() uint32 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *ListTransactionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTransactionsResponse) Reset() {
	*x = ListTransactionsResponse{}
	mi := &file_api_proto_plutus_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTransactionsResponse) ProtoMessage() {}

func (x *ListTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_plutus_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTransactionsResponse.ProtoReflect.Descriptor instead.
func (*ListTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_plutus_proto_rawDescGZIP(), []int{15}
}

func (x *ListTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ListTransactionsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListTransactionsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListTransactionsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_api_proto_plutus_proto protoreflect.FileDescriptor

const file_api_proto_plutus_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/plutus.proto\x12\tplutus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x02\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12\x1f\n" +
	"\vcustomer_id\x18\x03 \x01(\rR\n" +
	"customerId\x12\x18\n" +
	"\abalance\x18\x04 \x01(\x01R\abalance\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xc2\x03\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\rR\btenantId\x12\x1b\n" +
	"\twallet_id\x18\x03 \x01(\rR\bwalletId\x12\x19\n" +
	"\border_id\x18\x04 \x01(\rR\aorderId\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x16\n" +
	"\x06amount\x18\x06 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x18\n" +
	"\achannel\x18\b \x01(\tR\achannel\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\freference_no\x18\v \x01(\tR\vreferenceNo\x12\x12\n" +
	"\x04meta\x18\f \x01(\tR\x04meta\x129\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"R\n" +
	"\x13CreateWalletRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"A\n" +
	"\x14CreateWalletResponse\x12)\n" +
	"\x06wallet\x18\x01 \x01(\v2\x11.plutus.v1.WalletR\x06wallet\"\"\n" +
	"\x10GetWalletRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"?\n" +
	"\x1cGetWalletByCustomerIDRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\">\n" +
	"\x11GetWalletResponse\x12)\n" +
	"\x06wallet\x18\x01 \x01(\v2\x11.plutus.v1.WalletR\x06wallet\"E\n" +
	"\x12ListWalletsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x80\x01\n" +
	"\x13ListWalletsResponse\x12+\n" +
	"\awallets\x18\x01 \x03(\v2\x11.plutus.v1.WalletR\awallets\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\xe0\x01\n" +
	"\x0fRechargeRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\freference_no\x18\x06 \x01(\tR\vreferenceNo\x12\x12\n" +
	"\x04meta\x18\a \x01(\tR\x04meta\"\xbd\x01\n" +
	"\x0eConsumeRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\rR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04meta\x18\x06 \x01(\tR\x04meta\"\xdf\x01\n" +
	"\rRefundRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\rR\aorderId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x12!\n" +
	"\freference_no\x18\x06 \x01(\tR\vreferenceNo\x12\x12\n" +
	"\x04meta\x18\a \x01(\tR\x04meta\"O\n" +
	"\x13TransactionResponse\x128\n" +
	"\vtransaction\x18\x01 \x01(\v2\x16.plutus.v1.TransactionR\vtransaction\"'\n" +
	"\x15GetTransactionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"g\n" +
	"\x17ListTransactionsRequest\x12\x1b\n" +
	"\twallet_id\x18\x01 \x01(\rR\bwalletId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\x94\x01\n" +
	"\x18ListTransactionsResponse\x12:\n" +
	"\ftransactions\x18\x01 \x03(\v2\x16.plutus.v1.TransactionR\ftransactions\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size2\xd9\x05\n" +
	"\rWalletService\x12O\n" +
	"\fCreateWallet\x12\x1e.plutus.v1.CreateWalletRequest\x1a\x1f.plutus.v1.CreateWalletResponse\x12F\n" +
	"\tGetWallet\x12\x1b.plutus.v1.GetWalletRequest\x1a\x1c.plutus.v1.GetWalletResponse\x12^\n" +
	"\x15GetWalletByCustomerID\x12'.plutus.v1.GetWalletByCustomerIDRequest\x1a\x1c.plutus.v1.GetWalletResponse\x12L\n" +
	"\vListWallets\x12\x1d.plutus.v1.ListWalletsRequest\x1a\x1e.plutus.v1.ListWalletsResponse\x12F\n" +
	"\bRecharge\x12\x1a.plutus.v1.RechargeRequest\x1a\x1e.plutus.v1.TransactionResponse\x12D\n" +
	"\aConsume\x12\x19.plutus.v1.ConsumeRequest\x1a\x1e.plutus.v1.TransactionResponse\x12B\n" +
	"\x06Refund\x12\x18.plutus.v1.RefundRequest\x1a\x1e.plutus.v1.TransactionResponse\x12R\n" +
	"\x0eGetTransaction\x12 .plutus.v1.GetTransactionRequest\x1a\x1e.plutus.v1.TransactionResponse\x12[\n" +
	"\x10ListTransactions\x12\".plutus.v1.ListTransactionsRequest\x1a#.plutus.v1.ListTransactionsResponseB5Z3github.com/julesChu12/fly/plutus/api/proto;plutusv1b\x06proto3"

var (
	file_api_proto_plutus_proto_rawDescOnce sync.Once
	file_api_proto_plutus_proto_rawDescData []byte
)

func file_api_proto_plutus_proto_rawDescGZIP() []byte {
	file_api_proto_plutus_proto_rawDescOnce.Do(func() {
		file_api_proto_plutus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_plutus_proto_rawDesc), len(file_api_proto_plutus_proto_rawDesc)))
	})
	return file_api_proto_plutus_proto_rawDescData
}

var file_api_proto_plutus_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_proto_plutus_proto_goTypes = []any{
	(*Wallet)(nil),                       // 0: plutus.v1.Wallet
	(*Transaction)(nil),                  // 1: plutus.v1.Transaction
	(*CreateWalletRequest)(nil),          // 2: plutus.v1.CreateWalletRequest
	(*CreateWalletResponse)(nil),         // 3: plutus.v1.CreateWalletResponse
	(*GetWalletRequest)(nil),             // 4: plutus.v1.GetWalletRequest
	(*GetWalletByCustomerIDRequest)(nil), // 5: plutus.v1.GetWalletByCustomerIDRequest
	(*GetWalletResponse)(nil),            // 6: plutus.v1.GetWalletResponse
	(*ListWalletsRequest)(nil),           // 7: plutus.v1.ListWalletsRequest
	(*ListWalletsResponse)(nil),          // 8: plutus.v1.ListWalletsResponse
	(*RechargeRequest)(nil),              // 9: plutus.v1.RechargeRequest
	(*ConsumeRequest)(nil),               // 10: plutus.v1.ConsumeRequest
	(*RefundRequest)(nil),                // 11: plutus.v1.RefundRequest
	(*TransactionResponse)(nil),          // 12: plutus.v1.TransactionResponse
	(*GetTransactionRequest)(nil),        // 13: plutus.v1.GetTransactionRequest
	(*ListTransactionsRequest)(nil),      // 14: plutus.v1.ListTransactionsRequest
	(*ListTransactionsResponse)(nil),     // 15: plutus.v1.ListTransactionsResponse
	(*timestamppb.Timestamp)(nil),        // 16: google.protobuf.Timestamp
}
var file_api_proto_plutus_proto_depIdxs = []int32{
	16, // 0: plutus.v1.Wallet.created_at:type_name -> google.protobuf.Timestamp
	16, // 1: plutus.v1.Wallet.updated_at:type_name -> google.protobuf.Timestamp
	16, // 2: plutus.v1.Transaction.created_at:type_name -> google.protobuf.Timestamp
	16, // 3: plutus.v1.Transaction.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: plutus.v1.CreateWalletResponse.wallet:type_name -> plutus.v1.Wallet
	0,  // 5: plutus.v1.GetWalletResponse.wallet:type_name -> plutus.v1.Wallet
	0,  // 6: plutus.v1.ListWalletsResponse.wallets:type_name -> plutus.v1.Wallet
	1,  // 7: plutus.v1.TransactionResponse.transaction:type_name -> plutus.v1.Transaction
	1,  // 8: plutus.v1.ListTransactionsResponse.transactions:type_name -> plutus.v1.Transaction
	2,  // 9: plutus.v1.WalletService.CreateWallet:input_type -> plutus.v1.CreateWalletRequest
	4,  // 10: plutus.v1.WalletService.GetWallet:input_type -> plutus.v1.GetWalletRequest
	5,  // 11: plutus.v1.WalletService.GetWalletByCustomerID:input_type -> plutus.v1.GetWalletByCustomerIDRequest
	7,  // 12: plutus.v1.WalletService.ListWallets:input_type -> plutus.v1.ListWalletsRequest
	9,  // 13: plutus.v1.WalletService.Recharge:input_type -> plutus.v1.RechargeRequest
	10, // 14: plutus.v1.WalletService.Consume:input_type -> plutus.v1.ConsumeRequest
	11, // 15: plutus.v1.WalletService.Refund:input_type -> plutus.v1.RefundRequest
	13, // 16: plutus.v1.WalletService.GetTransaction:input_type -> plutus.v1.GetTransactionRequest
	14, // 17: plutus.v1.WalletService.ListTransactions:input_type -> plutus.v1.ListTransactionsRequest
	3,  // 18: plutus.v1.WalletService.CreateWallet:output_type -> plutus.v1.CreateWalletResponse
	6,  // 19: plutus.v1.WalletService.GetWallet:output_type -> plutus.v1.GetWalletResponse
	6,  // 20: plutus.v1.WalletService.GetWalletByCustomerID:output_type -> plutus.v1.GetWalletResponse
	8,  // 21: plutus.v1.WalletService.ListWallets:output_type -> plutus.v1.ListWalletsResponse
	12, // 22: plutus.v1.WalletService.Recharge:output_type -> plutus.v1.TransactionResponse
	12, // 23: plutus.v1.WalletService.Consume:output_type -> plutus.v1.TransactionResponse
	12, // 24: plutus.v1.WalletService.Refund:output_type -> plutus.v1.TransactionResponse
	12, // 25: plutus.v1.WalletService.GetTransaction:output_type -> plutus.v1.TransactionResponse
	15, // 26: plutus.v1.WalletService.ListTransactions:output_type -> plutus.v1.ListTransactionsResponse
	18, // [18:27] is the sub-list for method output_type
	9,  // [9:18] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_plutus_proto_init() }
func file_api_proto_plutus_proto_init() {
	if File_api_proto_plutus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_plutus_proto_rawDesc), len(file_api_proto_plutus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_plutus_proto_goTypes,
		DependencyIndexes: file_api_proto_plutus_proto_depIdxs,
		MessageInfos:      file_api_proto_plutus_proto_msgTypes,
	}.Build()
	File_api_proto_plutus_proto = out.File
	file_api_proto_plutus_proto_goTypes = nil
	file_api_proto_plutus_proto_depIdxs = nil
}
