// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/hermes.proto

package hermesv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Customer messages
type Customer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Contacts      []*Contact             `protobuf:"bytes,8,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Customer) Reset() {
	*x = Customer{}
	mi := &file_api_proto_hermes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Customer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Customer) ProtoMessage() {}

func (x *Customer) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Customer.ProtoReflect.Descriptor instead.
func (*Customer) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{0}
}

func (x *Customer) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Customer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Customer) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *Customer) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Customer) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *Customer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Customer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Customer) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

type Contact struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId    uint32                 `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,5,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Contact) Reset() {
	*x = Contact{}
	mi := &file_api_proto_hermes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contact) ProtoMessage() {}

func (x *Contact) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contact.ProtoReflect.Descriptor instead.
func (*Contact) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{1}
}

func (x *Contact) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Contact) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Contact) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Contact) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Contact) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

func (x *Contact) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Contact) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// Request/Response messages for Customer
type CreateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Tags          string                 `protobuf:"bytes,4,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerRequest) Reset() {
	*x = CreateCustomerRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerRequest) ProtoMessage() {}

func (x *CreateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerRequest.ProtoReflect.Descriptor instead.
func (*CreateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *CreateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateCustomerRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type CreateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCustomerResponse) Reset() {
	*x = CreateCustomerResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCustomerResponse) ProtoMessage() {}

func (x *CreateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCustomerResponse.ProtoReflect.Descriptor instead.
func (*CreateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type GetCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerRequest) Reset() {
	*x = GetCustomerRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerRequest) ProtoMessage() {}

func (x *GetCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerRequest.ProtoReflect.Descriptor instead.
func (*GetCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{4}
}

func (x *GetCustomerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerResponse) Reset() {
	*x = GetCustomerResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerResponse) ProtoMessage() {}

func (x *GetCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{5}
}

func (x *GetCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type GetCustomerWithContactsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCustomerWithContactsResponse) Reset() {
	*x = GetCustomerWithContactsResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCustomerWithContactsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCustomerWithContactsResponse) ProtoMessage() {}

func (x *GetCustomerWithContactsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCustomerWithContactsResponse.ProtoReflect.Descriptor instead.
func (*GetCustomerWithContactsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{6}
}

func (x *GetCustomerWithContactsResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type UpdateCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Tags          string                 `protobuf:"bytes,5,opt,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerRequest) Reset() {
	*x = UpdateCustomerRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerRequest) ProtoMessage() {}

func (x *UpdateCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerRequest.ProtoReflect.Descriptor instead.
func (*UpdateCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCustomerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateCustomerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCustomerRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UpdateCustomerRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UpdateCustomerRequest) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

type UpdateCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *Customer              `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCustomerResponse) Reset() {
	*x = UpdateCustomerResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCustomerResponse) ProtoMessage() {}

func (x *UpdateCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCustomerResponse.ProtoReflect.Descriptor instead.
func (*UpdateCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCustomerResponse) GetCustomer() *Customer {
	if x != nil {
		return x.Customer
	}
	return nil
}

type DeleteCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerRequest) Reset() {
	*x = DeleteCustomerRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerRequest) ProtoMessage() {}

func (x *DeleteCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerRequest.ProtoReflect.Descriptor instead.
func (*DeleteCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCustomerRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCustomerResponse) Reset() {
	*x = DeleteCustomerResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCustomerResponse) ProtoMessage() {}

func (x *DeleteCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCustomerResponse.ProtoReflect.Descriptor instead.
func (*DeleteCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteCustomerResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListCustomersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersRequest) Reset() {
	*x = ListCustomersRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersRequest) ProtoMessage() {}

func (x *ListCustomersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersRequest.ProtoReflect.Descriptor instead.
func (*ListCustomersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{11}
}

func (x *ListCustomersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListCustomersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customers     []*Customer            `protobuf:"bytes,1,rep,name=customers,proto3" json:"customers,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCustomersResponse) Reset() {
	*x = ListCustomersResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCustomersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCustomersResponse) ProtoMessage() {}

func (x *ListCustomersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCustomersResponse.ProtoReflect.Descriptor instead.
func (*ListCustomersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{12}
}

func (x *ListCustomersResponse) GetCustomers() []*Customer {
	if x != nil {
		return x.Customers
	}
	return nil
}

func (x *ListCustomersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListCustomersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCustomersResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// Request/Response messages for Contact
type CreateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactRequest) Reset() {
	*x = CreateContactRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactRequest) ProtoMessage() {}

func (x *CreateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactRequest.ProtoReflect.Descriptor instead.
func (*CreateContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{13}
}

func (x *CreateContactRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateContactRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateContactRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *CreateContactRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type CreateContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContactResponse) Reset() {
	*x = CreateContactResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContactResponse) ProtoMessage() {}

func (x *CreateContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContactResponse.ProtoReflect.Descriptor instead.
func (*CreateContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{14}
}

func (x *CreateContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type GetContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactRequest) Reset() {
	*x = GetContactRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactRequest) ProtoMessage() {}

func (x *GetContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactRequest.ProtoReflect.Descriptor instead.
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{15}
}

func (x *GetContactRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContactResponse) Reset() {
	*x = GetContactResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContactResponse) ProtoMessage() {}

func (x *GetContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContactResponse.ProtoReflect.Descriptor instead.
func (*GetContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{16}
}

func (x *GetContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type UpdateContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	IsPrimary     bool                   `protobuf:"varint,4,opt,name=is_primary,json=isPrimary,proto3" json:"is_primary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactRequest) Reset() {
	*x = UpdateContactRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactRequest) ProtoMessage() {}

func (x *UpdateContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactRequest.ProtoReflect.Descriptor instead.
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateContactRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateContactRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *UpdateContactRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateContactRequest) GetIsPrimary() bool {
	if x != nil {
		return x.IsPrimary
	}
	return false
}

type UpdateContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contact       *Contact               `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateContactResponse) Reset() {
	*x = UpdateContactResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateContactResponse) ProtoMessage() {}

func (x *UpdateContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateContactResponse.ProtoReflect.Descriptor instead.
func (*UpdateContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateContactResponse) GetContact() *Contact {
	if x != nil {
		return x.Contact
	}
	return nil
}

type DeleteContactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactRequest) Reset() {
	*x = DeleteContactRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactRequest) ProtoMessage() {}

func (x *DeleteContactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactRequest.ProtoReflect.Descriptor instead.
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteContactRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteContactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteContactResponse) Reset() {
	*x = DeleteContactResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteContactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteContactResponse) ProtoMessage() {}

func (x *DeleteContactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteContactResponse.ProtoReflect.Descriptor instead.
func (*DeleteContactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteContactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ListContactsByCustomerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    uint32                 `protobuf:"varint,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsByCustomerRequest) Reset() {
	*x = ListContactsByCustomerRequest{}
	mi := &file_api_proto_hermes_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsByCustomerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsByCustomerRequest) ProtoMessage() {}

func (x *ListContactsByCustomerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsByCustomerRequest.ProtoReflect.Descriptor instead.
func (*ListContactsByCustomerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{21}
}

func (x *ListContactsByCustomerRequest) GetCustomerId() uint32 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

type ListContactsByCustomerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contacts      []*Contact             `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListContactsByCustomerResponse) Reset() {
	*x = ListContactsByCustomerResponse{}
	mi := &file_api_proto_hermes_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListContactsByCustomerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListContactsByCustomerResponse) ProtoMessage() {}

func (x *ListContactsByCustomerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_hermes_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListContactsByCustomerResponse.ProtoReflect.Descriptor instead.
func (*ListContactsByCustomerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_hermes_proto_rawDescGZIP(), []int{22}
}

func (x *ListContactsByCustomerResponse) GetContacts() []*Contact {
	if x != nil {
		return x.Contacts
	}
	return nil
}

var File_api_proto_hermes_proto protoreflect.FileDescriptor

const file_api_proto_hermes_proto_rawDesc = "" +
	"\n" +
	"\x16api/proto/hermes.proto\x12\thermes.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x02\n" +
	"\bCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12.\n" +
	"\bcontacts\x18\b \x03(\v2\x12.hermes.v1.ContactR\bcontacts\"\xf9\x01\n" +
	"\aContact\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\rR\n" +
	"customerId\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x05 \x01(\bR\tisPrimary\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"k\n" +
	"\x15CreateCustomerRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x02 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x12\n" +
	"\x04tags\x18\x04 \x01(\tR\x04tags\"I\n" +
	"\x16CreateCustomerResponse\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.hermes.v1.CustomerR\bcustomer\"$\n" +
	"\x12GetCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"F\n" +
	"\x13GetCustomerResponse\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.hermes.v1.CustomerR\bcustomer\"R\n" +
	"\x1fGetCustomerWithContactsResponse\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.hermes.v1.CustomerR\bcustomer\"{\n" +
	"\x15UpdateCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05phone\x18\x03 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04tags\x18\x05 \x01(\tR\x04tags\"I\n" +
	"\x16UpdateCustomerResponse\x12/\n" +
	"\bcustomer\x18\x01 \x01(\v2\x13.hermes.v1.CustomerR\bcustomer\"'\n" +
	"\x15DeleteCustomerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"2\n" +
	"\x16DeleteCustomerResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"G\n" +
	"\x14ListCustomersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\"\x88\x01\n" +
	"\x15ListCustomersResponse\x121\n" +
	"\tcustomers\x18\x01 \x03(\v2\x13.hermes.v1.CustomerR\tcustomers\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\x80\x01\n" +
	"\x14CreateContactRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\"E\n" +
	"\x15CreateContactResponse\x12,\n" +
	"\acontact\x18\x01 \x01(\v2\x12.hermes.v1.ContactR\acontact\"#\n" +
	"\x11GetContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"B\n" +
	"\x12GetContactResponse\x12,\n" +
	"\acontact\x18\x01 \x01(\v2\x12.hermes.v1.ContactR\acontact\"o\n" +
	"\x14UpdateContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x1d\n" +
	"\n" +
	"is_primary\x18\x04 \x01(\bR\tisPrimary\"E\n" +
	"\x15UpdateContactResponse\x12,\n" +
	"\acontact\x18\x01 \x01(\v2\x12.hermes.v1.ContactR\acontact\"&\n" +
	"\x14DeleteContactRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"1\n" +
	"\x15DeleteContactResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"@\n" +
	"\x1dListContactsByCustomerRequest\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\rR\n" +
	"customerId\"P\n" +
	"\x1eListContactsByCustomerResponse\x12.\n" +
	"\bcontacts\x18\x01 \x03(\v2\x12.hermes.v1.ContactR\bcontacts2\x9e\x04\n" +
	"\x0fCustomerService\x12U\n" +
	"\x0eCreateCustomer\x12 .hermes.v1.CreateCustomerRequest\x1a!.hermes.v1.CreateCustomerResponse\x12L\n" +
	"\vGetCustomer\x12\x1d.hermes.v1.GetCustomerRequest\x1a\x1e.hermes.v1.GetCustomerResponse\x12d\n" +
	"\x17GetCustomerWithContacts\x12\x1d.hermes.v1.GetCustomerRequest\x1a*.hermes.v1.GetCustomerWithContactsResponse\x12U\n" +
	"\x0eUpdateCustomer\x12 .hermes.v1.UpdateCustomerRequest\x1a!.hermes.v1.UpdateCustomerResponse\x12U\n" +
	"\x0eDeleteCustomer\x12 .hermes.v1.DeleteCustomerRequest\x1a!.hermes.v1.DeleteCustomerResponse\x12R\n" +
	"\rListCustomers\x12\x1f.hermes.v1.ListCustomersRequest\x1a .hermes.v1.ListCustomersResponse2\xc6\x03\n" +
	"\x0eContactService\x12R\n" +
	"\rCreateContact\x12\x1f.hermes.v1.CreateContactRequest\x1a .hermes.v1.CreateContactResponse\x12I\n" +
	"\n" +
	"GetContact\x12\x1c.hermes.v1.GetContactRequest\x1a\x1d.hermes.v1.GetContactResponse\x12R\n" +
	"\rUpdateContact\x12\x1f.hermes.v1.UpdateContactRequest\x1a .hermes.v1.UpdateContactResponse\x12R\n" +
	"\rDeleteContact\x12\x1f.hermes.v1.DeleteContactRequest\x1a .hermes.v1.DeleteContactResponse\x12m\n" +
	"\x16ListContactsByCustomer\x12(.hermes.v1.ListContactsByCustomerRequest\x1a).hermes.v1.ListContactsByCustomerResponseB%Z#hermes/api/proto/hermes/v1;hermesv1b\x06proto3"

var (
	file_api_proto_hermes_proto_rawDescOnce sync.Once
	file_api_proto_hermes_proto_rawDescData []byte
)

func file_api_proto_hermes_proto_rawDescGZIP() []byte {
	file_api_proto_hermes_proto_rawDescOnce.Do(func() {
		file_api_proto_hermes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_hermes_proto_rawDesc), len(file_api_proto_hermes_proto_rawDesc)))
	})
	return file_api_proto_hermes_proto_rawDescData
}

var file_api_proto_hermes_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_hermes_proto_goTypes = []any{
	(*Customer)(nil),                        // 0: hermes.v1.Customer
	(*Contact)(nil),                         // 1: hermes.v1.Contact
	(*CreateCustomerRequest)(nil),           // 2: hermes.v1.CreateCustomerRequest
	(*CreateCustomerResponse)(nil),          // 3: hermes.v1.CreateCustomerResponse
	(*GetCustomerRequest)(nil),              // 4: hermes.v1.GetCustomerRequest
	(*GetCustomerResponse)(nil),             // 5: hermes.v1.GetCustomerResponse
	(*GetCustomerWithContactsResponse)(nil), // 6: hermes.v1.GetCustomerWithContactsResponse
	(*UpdateCustomerRequest)(nil),           // 7: hermes.v1.UpdateCustomerRequest
	(*UpdateCustomerResponse)(nil),          // 8: hermes.v1.UpdateCustomerResponse
	(*DeleteCustomerRequest)(nil),           // 9: hermes.v1.DeleteCustomerRequest
	(*DeleteCustomerResponse)(nil),          // 10: hermes.v1.DeleteCustomerResponse
	(*ListCustomersRequest)(nil),            // 11: hermes.v1.ListCustomersRequest
	(*ListCustomersResponse)(nil),           // 12: hermes.v1.ListCustomersResponse
	(*CreateContactRequest)(nil),            // 13: hermes.v1.CreateContactRequest
	(*CreateContactResponse)(nil),           // 14: hermes.v1.CreateContactResponse
	(*GetContactRequest)(nil),               // 15: hermes.v1.GetContactRequest
	(*GetContactResponse)(nil),              // 16: hermes.v1.GetContactResponse
	(*UpdateContactRequest)(nil),            // 17: hermes.v1.UpdateContactRequest
	(*UpdateContactResponse)(nil),           // 18: hermes.v1.UpdateContactResponse
	(*DeleteContactRequest)(nil),            // 19: hermes.v1.DeleteContactRequest
	(*DeleteContactResponse)(nil),           // 20: hermes.v1.DeleteContactResponse
	(*ListContactsByCustomerRequest)(nil),   // 21: hermes.v1.ListContactsByCustomerRequest
	(*ListContactsByCustomerResponse)(nil),  // 22: hermes.v1.ListContactsByCustomerResponse
	(*timestamppb.Timestamp)(nil),           // 23: google.protobuf.Timestamp
}
var file_api_proto_hermes_proto_depIdxs = []int32{
	23, // 0: hermes.v1.Customer.created_at:type_name -> google.protobuf.Timestamp
	23, // 1: hermes.v1.Customer.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: hermes.v1.Customer.contacts:type_name -> hermes.v1.Contact
	23, // 3: hermes.v1.Contact.created_at:type_name -> google.protobuf.Timestamp
	23, // 4: hermes.v1.Contact.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: hermes.v1.CreateCustomerResponse.customer:type_name -> hermes.v1.Customer
	0,  // 6: hermes.v1.GetCustomerResponse.customer:type_name -> hermes.v1.Customer
	0,  // 7: hermes.v1.GetCustomerWithContactsResponse.customer:type_name -> hermes.v1.Customer
	0,  // 8: hermes.v1.UpdateCustomerResponse.customer:type_name -> hermes.v1.Customer
	0,  // 9: hermes.v1.ListCustomersResponse.customers:type_name -> hermes.v1.Customer
	1,  // 10: hermes.v1.CreateContactResponse.contact:type_name -> hermes.v1.Contact
	1,  // 11: hermes.v1.GetContactResponse.contact:type_name -> hermes.v1.Contact
	1,  // 12: hermes.v1.UpdateContactResponse.contact:type_name -> hermes.v1.Contact
	1,  // 13: hermes.v1.ListContactsByCustomerResponse.contacts:type_name -> hermes.v1.Contact
	2,  // 14: hermes.v1.CustomerService.CreateCustomer:input_type -> hermes.v1.CreateCustomerRequest
	4,  // 15: hermes.v1.CustomerService.GetCustomer:input_type -> hermes.v1.GetCustomerRequest
	4,  // 16: hermes.v1.CustomerService.GetCustomerWithContacts:input_type -> hermes.v1.GetCustomerRequest
	7,  // 17: hermes.v1.CustomerService.UpdateCustomer:input_type -> hermes.v1.UpdateCustomerRequest
	9,  // 18: hermes.v1.CustomerService.DeleteCustomer:input_type -> hermes.v1.DeleteCustomerRequest
	11, // 19: hermes.v1.CustomerService.ListCustomers:input_type -> hermes.v1.ListCustomersRequest
	13, // 20: hermes.v1.ContactService.CreateContact:input_type -> hermes.v1.CreateContactRequest
	15, // 21: hermes.v1.ContactService.GetContact:input_type -> hermes.v1.GetContactRequest
	17, // 22: hermes.v1.ContactService.UpdateContact:input_type -> hermes.v1.UpdateContactRequest
	19, // 23: hermes.v1.ContactService.DeleteContact:input_type -> hermes.v1.DeleteContactRequest
	21, // 24: hermes.v1.ContactService.ListContactsByCustomer:input_type -> hermes.v1.ListContactsByCustomerRequest
	3,  // 25: hermes.v1.CustomerService.CreateCustomer:output_type -> hermes.v1.CreateCustomerResponse
	5,  // 26: hermes.v1.CustomerService.GetCustomer:output_type -> hermes.v1.GetCustomerResponse
	6,  // 27: hermes.v1.CustomerService.GetCustomerWithContacts:output_type -> hermes.v1.GetCustomerWithContactsResponse
	8,  // 28: hermes.v1.CustomerService.UpdateCustomer:output_type -> hermes.v1.UpdateCustomerResponse
	10, // 29: hermes.v1.CustomerService.DeleteCustomer:output_type -> hermes.v1.DeleteCustomerResponse
	12, // 30: hermes.v1.CustomerService.ListCustomers:output_type -> hermes.v1.ListCustomersResponse
	14, // 31: hermes.v1.ContactService.CreateContact:output_type -> hermes.v1.CreateContactResponse
	16, // 32: hermes.v1.ContactService.GetContact:output_type -> hermes.v1.GetContactResponse
	18, // 33: hermes.v1.ContactService.UpdateContact:output_type -> hermes.v1.UpdateContactResponse
	20, // 34: hermes.v1.ContactService.DeleteContact:output_type -> hermes.v1.DeleteContactResponse
	22, // 35: hermes.v1.ContactService.ListContactsByCustomer:output_type -> hermes.v1.ListContactsByCustomerResponse
	25, // [25:36] is the sub-list for method output_type
	14, // [14:25] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_hermes_proto_init() }
func file_api_proto_hermes_proto_init() {
	if File_api_proto_hermes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_hermes_proto_rawDesc), len(file_api_proto_hermes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_hermes_proto_goTypes,
		DependencyIndexes: file_api_proto_hermes_proto_depIdxs,
		MessageInfos:      file_api_proto_hermes_proto_msgTypes,
	}.Build()
	File_api_proto_hermes_proto = out.File
	file_api_proto_hermes_proto_goTypes = nil
	file_api_proto_hermes_proto_depIdxs = nil
}
