FROM golang:1.25.1-alpine

WORKDIR /app

# 基础工具
RUN apk add --no-cache git gcc musl-dev

# 安装 Air 热重载
RUN go install github.com/air-verse/air@latest

# 预拉依赖
COPY go.mod go.sum ./
RUN go mod download

# 拷贝源码（便于首次构建）；运行时会通过 volume 覆盖
COPY . .

EXPOSE 8080 9080

CMD ["air"]

