// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: api/proto/order/v1/order.proto

package orderv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OrderStatus represents the status of an order
type OrderStatus int32

const (
	OrderStatus_ORDER_STATUS_UNSPECIFIED OrderStatus = 0
	OrderStatus_ORDER_STATUS_PENDING     OrderStatus = 1
	OrderStatus_ORDER_STATUS_PAID        OrderStatus = 2
	OrderStatus_ORDER_STATUS_FULFILLED   OrderStatus = 3
	OrderStatus_ORDER_STATUS_CANCELED    OrderStatus = 4
)

// Enum value maps for OrderStatus.
var (
	OrderStatus_name = map[int32]string{
		0: "ORDER_STATUS_UNSPECIFIED",
		1: "ORDER_STATUS_PENDING",
		2: "ORDER_STATUS_PAID",
		3: "ORDER_STATUS_FULFILLED",
		4: "ORDER_STATUS_CANCELED",
	}
	OrderStatus_value = map[string]int32{
		"ORDER_STATUS_UNSPECIFIED": 0,
		"ORDER_STATUS_PENDING":     1,
		"ORDER_STATUS_PAID":        2,
		"ORDER_STATUS_FULFILLED":   3,
		"ORDER_STATUS_CANCELED":    4,
	}
)

func (x OrderStatus) Enum() *OrderStatus {
	p := new(OrderStatus)
	*p = x
	return p
}

func (x OrderStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_proto_order_v1_order_proto_enumTypes[0].Descriptor()
}

func (OrderStatus) Type() protoreflect.EnumType {
	return &file_api_proto_order_v1_order_proto_enumTypes[0]
}

func (x OrderStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderStatus.Descriptor instead.
func (OrderStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{0}
}

// Order represents an order entity
type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrderNo       string                 `protobuf:"bytes,3,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CustomerId    uint64                 `protobuf:"varint,4,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TotalAmount   float64                `protobuf:"fixed64,5,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency      string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Status        OrderStatus            `protobuf:"varint,7,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	Remark        string                 `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *Order) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Order) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *Order) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *Order) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *Order) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *Order) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Order) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *Order) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Order) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Order) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// OrderItem represents an order item entity
type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	ProductId     *uint64                `protobuf:"varint,4,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,5,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Sku           string                 `protobuf:"bytes,6,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,7,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,8,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	TotalPrice    float64                `protobuf:"fixed64,9,opt,name=total_price,json=totalPrice,proto3" json:"total_price,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderItem) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *OrderItem) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *OrderItem) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *OrderItem) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *OrderItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *OrderItem) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *OrderItem) GetTotalPrice() float64 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *OrderItem) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *OrderItem) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// OrderStatusLog represents a status change log
type OrderStatusLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      uint64                 `protobuf:"varint,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	FromStatus    *OrderStatus           `protobuf:"varint,4,opt,name=from_status,json=fromStatus,proto3,enum=order.v1.OrderStatus,oneof" json:"from_status,omitempty"`
	ToStatus      OrderStatus            `protobuf:"varint,5,opt,name=to_status,json=toStatus,proto3,enum=order.v1.OrderStatus" json:"to_status,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	OperatorId    *uint64                `protobuf:"varint,7,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderStatusLog) Reset() {
	*x = OrderStatusLog{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStatusLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStatusLog) ProtoMessage() {}

func (x *OrderStatusLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStatusLog.ProtoReflect.Descriptor instead.
func (*OrderStatusLog) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderStatusLog) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OrderStatusLog) GetTenantId() uint64 {
	if x != nil {
		return x.TenantId
	}
	return 0
}

func (x *OrderStatusLog) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderStatusLog) GetFromStatus() OrderStatus {
	if x != nil && x.FromStatus != nil {
		return *x.FromStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderStatusLog) GetToStatus() OrderStatus {
	if x != nil {
		return x.ToStatus
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *OrderStatusLog) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OrderStatusLog) GetOperatorId() uint64 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

func (x *OrderStatusLog) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// CreateOrderRequest represents the request to create an order
type CreateOrderRequest struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	OrderNo       string                    `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	CustomerId    uint64                    `protobuf:"varint,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	TotalAmount   float64                   `protobuf:"fixed64,3,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	Currency      string                    `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Remark        string                    `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Items         []*CreateOrderItemRequest `protobuf:"bytes,6,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrderRequest) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *CreateOrderRequest) GetCustomerId() uint64 {
	if x != nil {
		return x.CustomerId
	}
	return 0
}

func (x *CreateOrderRequest) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *CreateOrderRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateOrderRequest) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *CreateOrderRequest) GetItems() []*CreateOrderItemRequest {
	if x != nil {
		return x.Items
	}
	return nil
}

// CreateOrderItemRequest represents an order item in create request
type CreateOrderItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     *uint64                `protobuf:"varint,1,opt,name=product_id,json=productId,proto3,oneof" json:"product_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,2,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Sku           string                 `protobuf:"bytes,3,opt,name=sku,proto3" json:"sku,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,5,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderItemRequest) Reset() {
	*x = CreateOrderItemRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderItemRequest) ProtoMessage() {}

func (x *CreateOrderItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderItemRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *CreateOrderItemRequest) GetProductId() uint64 {
	if x != nil && x.ProductId != nil {
		return *x.ProductId
	}
	return 0
}

func (x *CreateOrderItemRequest) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *CreateOrderItemRequest) GetSku() string {
	if x != nil {
		return x.Sku
	}
	return ""
}

func (x *CreateOrderItemRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *CreateOrderItemRequest) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

// GetOrderRequest represents the request to get an order
type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrderRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// ListOrdersRequest represents the request to list orders
type ListOrdersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	CustomerId    *uint64                `protobuf:"varint,3,opt,name=customer_id,json=customerId,proto3,oneof" json:"customer_id,omitempty"`
	Status        *OrderStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=order.v1.OrderStatus,oneof" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersRequest) Reset() {
	*x = ListOrdersRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersRequest) ProtoMessage() {}

func (x *ListOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersRequest.ProtoReflect.Descriptor instead.
func (*ListOrdersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{6}
}

func (x *ListOrdersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListOrdersRequest) GetCustomerId() uint64 {
	if x != nil && x.CustomerId != nil {
		return *x.CustomerId
	}
	return 0
}

func (x *ListOrdersRequest) GetStatus() OrderStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

// UpdateOrderStatusRequest represents the request to update order status
type UpdateOrderStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        OrderStatus            `protobuf:"varint,2,opt,name=status,proto3,enum=order.v1.OrderStatus" json:"status,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	OperatorId    *uint64                `protobuf:"varint,4,opt,name=operator_id,json=operatorId,proto3,oneof" json:"operator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOrderStatusRequest) Reset() {
	*x = UpdateOrderStatusRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOrderStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOrderStatusRequest) ProtoMessage() {}

func (x *UpdateOrderStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOrderStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateOrderStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateOrderStatusRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateOrderStatusRequest) GetStatus() OrderStatus {
	if x != nil {
		return x.Status
	}
	return OrderStatus_ORDER_STATUS_UNSPECIFIED
}

func (x *UpdateOrderStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *UpdateOrderStatusRequest) GetOperatorId() uint64 {
	if x != nil && x.OperatorId != nil {
		return *x.OperatorId
	}
	return 0
}

// DeleteOrderRequest represents the request to delete an order
type DeleteOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderRequest) Reset() {
	*x = DeleteOrderRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderRequest) ProtoMessage() {}

func (x *DeleteOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderRequest.ProtoReflect.Descriptor instead.
func (*DeleteOrderRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteOrderRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

// GetOrderLogsRequest represents the request to get order logs
type GetOrderLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       uint64                 `protobuf:"varint,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLogsRequest) Reset() {
	*x = GetOrderLogsRequest{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLogsRequest) ProtoMessage() {}

func (x *GetOrderLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLogsRequest.ProtoReflect.Descriptor instead.
func (*GetOrderLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderLogsRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

// OrderResponse represents the response containing an order
type OrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderResponse) Reset() {
	*x = OrderResponse{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderResponse) ProtoMessage() {}

func (x *OrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderResponse.ProtoReflect.Descriptor instead.
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{10}
}

func (x *OrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

// OrderWithItemsResponse represents the response containing an order with items
type OrderWithItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Items         []*OrderItem           `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderWithItemsResponse) Reset() {
	*x = OrderWithItemsResponse{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderWithItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderWithItemsResponse) ProtoMessage() {}

func (x *OrderWithItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderWithItemsResponse.ProtoReflect.Descriptor instead.
func (*OrderWithItemsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{11}
}

func (x *OrderWithItemsResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

func (x *OrderWithItemsResponse) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

// ListOrdersResponse represents the response containing a list of orders
type ListOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListOrdersResponse) Reset() {
	*x = ListOrdersResponse{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListOrdersResponse) ProtoMessage() {}

func (x *ListOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListOrdersResponse.ProtoReflect.Descriptor instead.
func (*ListOrdersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{12}
}

func (x *ListOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *ListOrdersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListOrdersResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListOrdersResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

// DeleteOrderResponse represents the response for delete operation
type DeleteOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOrderResponse) Reset() {
	*x = DeleteOrderResponse{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOrderResponse) ProtoMessage() {}

func (x *DeleteOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOrderResponse.ProtoReflect.Descriptor instead.
func (*DeleteOrderResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteOrderResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteOrderResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// GetOrderLogsResponse represents the response containing order logs
type GetOrderLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          []*OrderStatusLog      `protobuf:"bytes,1,rep,name=logs,proto3" json:"logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderLogsResponse) Reset() {
	*x = GetOrderLogsResponse{}
	mi := &file_api_proto_order_v1_order_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderLogsResponse) ProtoMessage() {}

func (x *GetOrderLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_order_v1_order_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderLogsResponse.ProtoReflect.Descriptor instead.
func (*GetOrderLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_order_v1_order_proto_rawDescGZIP(), []int{14}
}

func (x *GetOrderLogsResponse) GetLogs() []*OrderStatusLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

var File_api_proto_order_v1_order_proto protoreflect.FileDescriptor

const file_api_proto_order_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/order/v1/order.proto\x12\border.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x02\n" +
	"\x05Order\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x19\n" +
	"\border_no\x18\x03 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vcustomer_id\x18\x04 \x01(\x04R\n" +
	"customerId\x12!\n" +
	"\ftotal_amount\x18\x05 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12-\n" +
	"\x06status\x18\a \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\x12\x16\n" +
	"\x06remark\x18\b \x01(\tR\x06remark\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x8d\x03\n" +
	"\tOrderItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12\"\n" +
	"\n" +
	"product_id\x18\x04 \x01(\x04H\x00R\tproductId\x88\x01\x01\x12!\n" +
	"\fproduct_name\x18\x05 \x01(\tR\vproductName\x12\x10\n" +
	"\x03sku\x18\x06 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\a \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\b \x01(\x01R\tunitPrice\x12\x1f\n" +
	"\vtotal_price\x18\t \x01(\x01R\n" +
	"totalPrice\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\r\n" +
	"\v_product_id\"\xe2\x02\n" +
	"\x0eOrderStatusLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\x04R\btenantId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\x04R\aorderId\x12;\n" +
	"\vfrom_status\x18\x04 \x01(\x0e2\x15.order.v1.OrderStatusH\x00R\n" +
	"fromStatus\x88\x01\x01\x122\n" +
	"\tto_status\x18\x05 \x01(\x0e2\x15.order.v1.OrderStatusR\btoStatus\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12$\n" +
	"\voperator_id\x18\a \x01(\x04H\x01R\n" +
	"operatorId\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAtB\x0e\n" +
	"\f_from_statusB\x0e\n" +
	"\f_operator_id\"\xdf\x01\n" +
	"\x12CreateOrderRequest\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\x04R\n" +
	"customerId\x12!\n" +
	"\ftotal_amount\x18\x03 \x01(\x01R\vtotalAmount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06remark\x18\x05 \x01(\tR\x06remark\x126\n" +
	"\x05items\x18\x06 \x03(\v2 .order.v1.CreateOrderItemRequestR\x05items\"\xbb\x01\n" +
	"\x16CreateOrderItemRequest\x12\"\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04H\x00R\tproductId\x88\x01\x01\x12!\n" +
	"\fproduct_name\x18\x02 \x01(\tR\vproductName\x12\x10\n" +
	"\x03sku\x18\x03 \x01(\tR\x03sku\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x05 \x01(\x01R\tunitPriceB\r\n" +
	"\v_product_id\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"\xb9\x01\n" +
	"\x11ListOrdersRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12$\n" +
	"\vcustomer_id\x18\x03 \x01(\x04H\x00R\n" +
	"customerId\x88\x01\x01\x122\n" +
	"\x06status\x18\x04 \x01(\x0e2\x15.order.v1.OrderStatusH\x01R\x06status\x88\x01\x01B\x0e\n" +
	"\f_customer_idB\t\n" +
	"\a_status\"\xa7\x01\n" +
	"\x18UpdateOrderStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12-\n" +
	"\x06status\x18\x02 \x01(\x0e2\x15.order.v1.OrderStatusR\x06status\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12$\n" +
	"\voperator_id\x18\x04 \x01(\x04H\x00R\n" +
	"operatorId\x88\x01\x01B\x0e\n" +
	"\f_operator_id\"$\n" +
	"\x12DeleteOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"0\n" +
	"\x13GetOrderLogsRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\x04R\aorderId\"6\n" +
	"\rOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\"j\n" +
	"\x16OrderWithItemsResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.order.v1.OrderR\x05order\x12)\n" +
	"\x05items\x18\x02 \x03(\v2\x13.order.v1.OrderItemR\x05items\"{\n" +
	"\x12ListOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.order.v1.OrderR\x06orders\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"I\n" +
	"\x13DeleteOrderResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"D\n" +
	"\x14GetOrderLogsResponse\x12,\n" +
	"\x04logs\x18\x01 \x03(\v2\x18.order.v1.OrderStatusLogR\x04logs*\x93\x01\n" +
	"\vOrderStatus\x12\x1c\n" +
	"\x18ORDER_STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14ORDER_STATUS_PENDING\x10\x01\x12\x15\n" +
	"\x11ORDER_STATUS_PAID\x10\x02\x12\x1a\n" +
	"\x16ORDER_STATUS_FULFILLED\x10\x03\x12\x19\n" +
	"\x15ORDER_STATUS_CANCELED\x10\x042\x9c\x04\n" +
	"\fOrderService\x12D\n" +
	"\vCreateOrder\x12\x1c.order.v1.CreateOrderRequest\x1a\x17.order.v1.OrderResponse\x12>\n" +
	"\bGetOrder\x12\x19.order.v1.GetOrderRequest\x1a\x17.order.v1.OrderResponse\x12P\n" +
	"\x11GetOrderWithItems\x12\x19.order.v1.GetOrderRequest\x1a .order.v1.OrderWithItemsResponse\x12G\n" +
	"\n" +
	"ListOrders\x12\x1b.order.v1.ListOrdersRequest\x1a\x1c.order.v1.ListOrdersResponse\x12P\n" +
	"\x11UpdateOrderStatus\x12\".order.v1.UpdateOrderStatusRequest\x1a\x17.order.v1.OrderResponse\x12J\n" +
	"\vDeleteOrder\x12\x1c.order.v1.DeleteOrderRequest\x1a\x1d.order.v1.DeleteOrderResponse\x12M\n" +
	"\fGetOrderLogs\x12\x1d.order.v1.GetOrderLogsRequest\x1a\x1e.order.v1.GetOrderLogsResponseB=Z;github.com/julesChu12/fly/kratos/api/proto/order/v1;orderv1b\x06proto3"

var (
	file_api_proto_order_v1_order_proto_rawDescOnce sync.Once
	file_api_proto_order_v1_order_proto_rawDescData []byte
)

func file_api_proto_order_v1_order_proto_rawDescGZIP() []byte {
	file_api_proto_order_v1_order_proto_rawDescOnce.Do(func() {
		file_api_proto_order_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_order_v1_order_proto_rawDesc), len(file_api_proto_order_v1_order_proto_rawDesc)))
	})
	return file_api_proto_order_v1_order_proto_rawDescData
}

var file_api_proto_order_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_proto_order_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_order_v1_order_proto_goTypes = []any{
	(OrderStatus)(0),                 // 0: order.v1.OrderStatus
	(*Order)(nil),                    // 1: order.v1.Order
	(*OrderItem)(nil),                // 2: order.v1.OrderItem
	(*OrderStatusLog)(nil),           // 3: order.v1.OrderStatusLog
	(*CreateOrderRequest)(nil),       // 4: order.v1.CreateOrderRequest
	(*CreateOrderItemRequest)(nil),   // 5: order.v1.CreateOrderItemRequest
	(*GetOrderRequest)(nil),          // 6: order.v1.GetOrderRequest
	(*ListOrdersRequest)(nil),        // 7: order.v1.ListOrdersRequest
	(*UpdateOrderStatusRequest)(nil), // 8: order.v1.UpdateOrderStatusRequest
	(*DeleteOrderRequest)(nil),       // 9: order.v1.DeleteOrderRequest
	(*GetOrderLogsRequest)(nil),      // 10: order.v1.GetOrderLogsRequest
	(*OrderResponse)(nil),            // 11: order.v1.OrderResponse
	(*OrderWithItemsResponse)(nil),   // 12: order.v1.OrderWithItemsResponse
	(*ListOrdersResponse)(nil),       // 13: order.v1.ListOrdersResponse
	(*DeleteOrderResponse)(nil),      // 14: order.v1.DeleteOrderResponse
	(*GetOrderLogsResponse)(nil),     // 15: order.v1.GetOrderLogsResponse
	(*timestamppb.Timestamp)(nil),    // 16: google.protobuf.Timestamp
}
var file_api_proto_order_v1_order_proto_depIdxs = []int32{
	0,  // 0: order.v1.Order.status:type_name -> order.v1.OrderStatus
	16, // 1: order.v1.Order.created_at:type_name -> google.protobuf.Timestamp
	16, // 2: order.v1.Order.updated_at:type_name -> google.protobuf.Timestamp
	16, // 3: order.v1.OrderItem.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: order.v1.OrderItem.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 5: order.v1.OrderStatusLog.from_status:type_name -> order.v1.OrderStatus
	0,  // 6: order.v1.OrderStatusLog.to_status:type_name -> order.v1.OrderStatus
	16, // 7: order.v1.OrderStatusLog.created_at:type_name -> google.protobuf.Timestamp
	5,  // 8: order.v1.CreateOrderRequest.items:type_name -> order.v1.CreateOrderItemRequest
	0,  // 9: order.v1.ListOrdersRequest.status:type_name -> order.v1.OrderStatus
	0,  // 10: order.v1.UpdateOrderStatusRequest.status:type_name -> order.v1.OrderStatus
	1,  // 11: order.v1.OrderResponse.order:type_name -> order.v1.Order
	1,  // 12: order.v1.OrderWithItemsResponse.order:type_name -> order.v1.Order
	2,  // 13: order.v1.OrderWithItemsResponse.items:type_name -> order.v1.OrderItem
	1,  // 14: order.v1.ListOrdersResponse.orders:type_name -> order.v1.Order
	3,  // 15: order.v1.GetOrderLogsResponse.logs:type_name -> order.v1.OrderStatusLog
	4,  // 16: order.v1.OrderService.CreateOrder:input_type -> order.v1.CreateOrderRequest
	6,  // 17: order.v1.OrderService.GetOrder:input_type -> order.v1.GetOrderRequest
	6,  // 18: order.v1.OrderService.GetOrderWithItems:input_type -> order.v1.GetOrderRequest
	7,  // 19: order.v1.OrderService.ListOrders:input_type -> order.v1.ListOrdersRequest
	8,  // 20: order.v1.OrderService.UpdateOrderStatus:input_type -> order.v1.UpdateOrderStatusRequest
	9,  // 21: order.v1.OrderService.DeleteOrder:input_type -> order.v1.DeleteOrderRequest
	10, // 22: order.v1.OrderService.GetOrderLogs:input_type -> order.v1.GetOrderLogsRequest
	11, // 23: order.v1.OrderService.CreateOrder:output_type -> order.v1.OrderResponse
	11, // 24: order.v1.OrderService.GetOrder:output_type -> order.v1.OrderResponse
	12, // 25: order.v1.OrderService.GetOrderWithItems:output_type -> order.v1.OrderWithItemsResponse
	13, // 26: order.v1.OrderService.ListOrders:output_type -> order.v1.ListOrdersResponse
	11, // 27: order.v1.OrderService.UpdateOrderStatus:output_type -> order.v1.OrderResponse
	14, // 28: order.v1.OrderService.DeleteOrder:output_type -> order.v1.DeleteOrderResponse
	15, // 29: order.v1.OrderService.GetOrderLogs:output_type -> order.v1.GetOrderLogsResponse
	23, // [23:30] is the sub-list for method output_type
	16, // [16:23] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_api_proto_order_v1_order_proto_init() }
func file_api_proto_order_v1_order_proto_init() {
	if File_api_proto_order_v1_order_proto != nil {
		return
	}
	file_api_proto_order_v1_order_proto_msgTypes[1].OneofWrappers = []any{}
	file_api_proto_order_v1_order_proto_msgTypes[2].OneofWrappers = []any{}
	file_api_proto_order_v1_order_proto_msgTypes[4].OneofWrappers = []any{}
	file_api_proto_order_v1_order_proto_msgTypes[6].OneofWrappers = []any{}
	file_api_proto_order_v1_order_proto_msgTypes[7].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_order_v1_order_proto_rawDesc), len(file_api_proto_order_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_order_v1_order_proto_goTypes,
		DependencyIndexes: file_api_proto_order_v1_order_proto_depIdxs,
		EnumInfos:         file_api_proto_order_v1_order_proto_enumTypes,
		MessageInfos:      file_api_proto_order_v1_order_proto_msgTypes,
	}.Build()
	File_api_proto_order_v1_order_proto = out.File
	file_api_proto_order_v1_order_proto_goTypes = nil
	file_api_proto_order_v1_order_proto_depIdxs = nil
}
